import { StyleSheet } from 'react-native';

/**
 * Fixed dark navy/cyan identity for the auth screens only — deliberately
 * independent from `theme.ts` (which drives the rest of the app and follows
 * the system light/dark scheme). This is a branded "showcase" screen, like
 * most products' login pages, so it doesn't adapt to the viewer's OS theme.
 */
export const authColors = {
  pageBg: '#040B18',
  pageBgTop: '#0A1730',
  cardBg: 'rgba(13, 25, 48, 0.78)',
  cardBorder: 'rgba(86, 189, 248, 0.35)',
  inputBg: 'rgba(6, 15, 32, 0.85)',
  inputBorder: 'rgba(255, 255, 255, 0.08)',
  textPrimary: '#F3F7FF',
  textSecondary: '#93A5C9',
  textMuted: '#5E749E',
  accentCyan: '#38BDF8',
  accentBlue: '#2563EB',
  danger: '#FF7A7A',
  divider: 'rgba(255, 255, 255, 0.12)',
  blobBlue: 'rgba(37, 99, 235, 0.30)',
  blobCyan: 'rgba(56, 189, 248, 0.18)',
};

export const fontFamilies = {
  displayRegular: 'Poppins_400Regular',
  displaySemiBold: 'Poppins_600SemiBold',
  displayBold: 'Poppins_700Bold',
  displayExtraBold: 'Poppins_800ExtraBold',
  script: 'Caveat_600SemiBold',
};

export function makeAuthStyles() {
  return StyleSheet.create({
    page: {
      flex: 1,
      minHeight: '100%',
      flexDirection: 'column',
      backgroundColor: authColors.pageBg,
      overflow: 'hidden',
    },
    stage: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    blob: {
      position: 'absolute',
      borderRadius: 9999,
    },
    blobTopLeftOuter: {
      width: 620,
      height: 620,
      top: -260,
      left: -260,
      backgroundColor: authColors.blobBlue,
    },
    blobTopLeftInner: {
      width: 340,
      height: 340,
      top: -120,
      left: -80,
      backgroundColor: authColors.blobCyan,
    },
    blobBottomRightOuter: {
      width: 680,
      height: 680,
      bottom: -300,
      right: -280,
      backgroundColor: authColors.blobBlue,
    },
    blobBottomRightInner: {
      width: 380,
      height: 380,
      bottom: -140,
      right: -100,
      backgroundColor: authColors.blobCyan,
    },
    langSelectorRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      paddingTop: 20,
      paddingRight: 24,
      zIndex: 2,
    },
    langSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(13, 25, 48, 0.6)',
      borderWidth: 1,
      borderColor: authColors.cardBorder,
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 16,
      zIndex: 2,
    },
    langSelectorText: {
      color: authColors.textPrimary,
      fontFamily: fontFamilies.displaySemiBold,
      fontSize: 13,
    },
    contentRow: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      maxWidth: 1440,
      width: '100%',
      alignSelf: 'center',
      gap: 32,
      zIndex: 1,
    },
    contentRowCentered: {
      justifyContent: 'center',
    },
    leftPanel: {
      flex: 1,
      maxWidth: 420,
    },
    leftHeadline: {
      fontFamily: fontFamilies.displayExtraBold,
      fontSize: 44,
      lineHeight: 52,
      color: authColors.textPrimary,
    },
    leftHeadlineAccent: {
      color: authColors.accentCyan,
    },
    leftDivider: {
      width: 56,
      height: 3,
      borderRadius: 2,
      backgroundColor: authColors.accentCyan,
      marginVertical: 20,
    },
    leftParagraph: {
      fontFamily: fontFamilies.displayRegular,
      fontSize: 16,
      lineHeight: 24,
      color: authColors.textSecondary,
    },
    rightPanel: {
      flex: 1,
      maxWidth: 420,
      alignItems: 'flex-end',
    },
    rightScript: {
      fontFamily: fontFamilies.script,
      fontSize: 34,
      color: authColors.textPrimary,
      textAlign: 'right',
    },
    rightScriptSecond: {
      color: authColors.accentCyan,
      marginTop: -6,
    },
    rightUnderline: {
      width: 120,
      height: 2,
      borderRadius: 2,
      backgroundColor: authColors.accentCyan,
      marginTop: 12,
      opacity: 0.6,
    },
    card: {
      width: '100%',
      maxWidth: 560,
      backgroundColor: authColors.cardBg,
      borderRadius: 32,
      borderWidth: 1,
      borderColor: authColors.cardBorder,
      paddingVertical: 32,
      paddingHorizontal: 40,
      shadowColor: authColors.accentBlue,
      shadowOffset: { width: 0, height: 20 },
      shadowOpacity: 0.35,
      shadowRadius: 40,
      elevation: 12,
    },
    cardNarrow: {
      borderRadius: 24,
      paddingVertical: 28,
      paddingHorizontal: 20,
    },
    logo: {
      width: 190,
      height: 64,
      alignSelf: 'center',
    },
    tagline: {
      fontFamily: fontFamilies.displayRegular,
      fontSize: 14,
      color: authColors.textSecondary,
      textAlign: 'center',
      marginTop: 8,
      lineHeight: 20,
    },
    welcomeTitle: {
      fontFamily: fontFamilies.displayExtraBold,
      fontSize: 24,
      color: authColors.textPrimary,
      textAlign: 'center',
      marginTop: 20,
    },
    welcomeSubtitle: {
      fontFamily: fontFamilies.displayRegular,
      fontSize: 14,
      color: authColors.textSecondary,
      textAlign: 'center',
      marginTop: 6,
      marginBottom: 20,
    },
    form: { width: '100%' },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: authColors.inputBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: authColors.inputBorder,
      paddingHorizontal: 18,
      height: 52,
      marginBottom: 12,
      gap: 12,
    },
    inputField: {
      flex: 1,
      fontFamily: fontFamilies.displayRegular,
      fontSize: 15,
      color: authColors.textPrimary,
      height: '100%',
    },
    error: { fontFamily: fontFamilies.displaySemiBold, fontSize: 13, color: authColors.danger, marginBottom: 12, textAlign: 'center' },
    primaryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      borderRadius: 16,
      paddingVertical: 15,
      marginTop: 4,
      shadowColor: authColors.accentCyan,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 20,
      elevation: 6,
    },
    buttonDisabled: { opacity: 0.6 },
    primaryButtonText: {
      color: '#FFFFFF',
      fontFamily: fontFamilies.displayBold,
      fontSize: 16,
      letterSpacing: 0.6,
    },
    linkRow: { marginTop: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 4 },
    linkTextMuted: { color: authColors.textSecondary, fontFamily: fontFamilies.displayRegular, fontSize: 14 },
    linkText: { color: authColors.accentCyan, fontFamily: fontFamilies.displaySemiBold, fontSize: 14 },
    dividerRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 16, gap: 12 },
    dividerLine: { flex: 1, height: 1, backgroundColor: authColors.divider },
    dividerText: { color: authColors.textMuted, fontFamily: fontFamilies.displayRegular, fontSize: 13 },
    socialButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      backgroundColor: authColors.inputBg,
      borderWidth: 1,
      borderColor: authColors.inputBorder,
      borderRadius: 16,
      paddingVertical: 13,
      marginBottom: 10,
    },
    socialButtonText: { color: authColors.textPrimary, fontFamily: fontFamilies.displaySemiBold, fontSize: 14 },
    benefitsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 18,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: authColors.divider,
    },
    benefitItem: { flex: 1, alignItems: 'center', gap: 8 },
    benefitText: {
      color: authColors.textSecondary,
      fontFamily: fontFamilies.displayRegular,
      fontSize: 11,
      textAlign: 'center',
      lineHeight: 15,
    },
  });
}
