import { StyleSheet } from 'react-native';
import { authColors, fontFamilies, liftStyle } from './authStyles';

export { authColors, fontFamilies, liftStyle };

export function makeDashboardStyles() {
  return StyleSheet.create({
    shell: {
      flex: 1,
      minHeight: '100%',
      flexDirection: 'row',
      backgroundColor: authColors.pageBg,
    },

    // Sidebar
    sidebar: {
      width: 264,
      backgroundColor: authColors.pageBg,
      borderRightWidth: 1,
      borderRightColor: authColors.divider,
      paddingVertical: 28,
      paddingHorizontal: 20,
      justifyContent: 'space-between',
    },
    sidebarTop: {},
    sidebarLogo: { width: 150, height: 50, alignSelf: 'center' },
    sidebarTagline: {
      textAlign: 'center',
      fontFamily: fontFamilies.displayRegular,
      fontSize: 12,
      color: authColors.textSecondary,
      marginTop: 8,
      marginBottom: 28,
      lineHeight: 16,
    },
    navItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 14,
      marginBottom: 6,
    },
    navItemActive: {
      backgroundColor: 'rgba(37, 99, 235, 0.28)',
      borderWidth: 1,
      borderColor: authColors.accentCyan,
      shadowColor: authColors.accentCyan,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 12,
      elevation: 4,
    },
    navItemIcon: { fontSize: 17, width: 20, textAlign: 'center' },
    navItemLabel: { fontFamily: fontFamilies.displaySemiBold, fontSize: 14, color: authColors.textSecondary },
    navItemLabelActive: { color: authColors.textPrimary },
    sidebarBottom: {},
    sidebarQuoteCard: {
      backgroundColor: authColors.cardBg,
      borderWidth: 1,
      borderColor: authColors.cardBorder,
      borderRadius: 16,
      padding: 16,
      marginBottom: 14,
    },
    sidebarQuoteFlag: { fontSize: 20, marginBottom: 8 },
    sidebarQuoteLu: { fontFamily: fontFamilies.displaySemiBold, fontSize: 13, color: authColors.textPrimary, lineHeight: 18 },
    sidebarQuotePt: { fontFamily: fontFamilies.displayRegular, fontSize: 11, color: authColors.textSecondary, marginTop: 6 },
    sidebarCopyright: {
      textAlign: 'center',
      fontFamily: fontFamilies.displayRegular,
      fontSize: 10,
      color: authColors.textMuted,
      lineHeight: 15,
    },

    // Mobile top bar (narrow layout replacement for the sidebar header)
    mobileTopBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 8,
    },
    mobileLogo: { width: 34, height: 34 },
    mobileLogoText: { fontFamily: fontFamilies.displayExtraBold, fontSize: 16, color: authColors.textPrimary },

    // Content area
    contentArea: { flex: 1 },
    contentScroll: { paddingBottom: 60 },

    // Top bar (search + stats + profile)
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      gap: 12,
      paddingHorizontal: 28,
      paddingTop: 24,
      paddingBottom: 20,
      position: 'relative',
      zIndex: 10,
    },
    searchWrapper: {
      flex: 1,
      minWidth: 200,
      maxWidth: 420,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: authColors.inputBg,
      borderWidth: 1,
      borderColor: authColors.inputBorder,
      borderRadius: 14,
      paddingHorizontal: 16,
      height: 46,
    },
    searchInput: { flex: 1, fontFamily: fontFamilies.displayRegular, fontSize: 14, color: authColors.textPrimary },
    statsRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 10 },
    // Without an explicit width, a wrapped flex item can still report its
    // own *unwrapped* content width upward and overflow the viewport — this
    // pins it to the line's available width so its own children truly wrap.
    statsRowNarrow: { width: '100%' },
    statPill: {
      alignItems: 'center',
      backgroundColor: authColors.cardBg,
      borderWidth: 1,
      borderColor: authColors.cardBorder,
      borderRadius: 14,
      paddingVertical: 8,
      paddingHorizontal: 14,
      minWidth: 76,
    },
    statPillValue: { fontFamily: fontFamilies.displayBold, fontSize: 15, color: authColors.textPrimary },
    statPillLabel: { fontFamily: fontFamilies.displayRegular, fontSize: 10, color: authColors.textSecondary, marginTop: 2 },
    profilePillWrap: { position: 'relative' },
    profilePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: authColors.cardBg,
      borderWidth: 1,
      borderColor: authColors.cardBorder,
      borderRadius: 999,
      paddingVertical: 6,
      paddingHorizontal: 10,
      paddingRight: 14,
    },
    profileAvatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: authColors.accentBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    profileAvatarText: { color: '#FFFFFF', fontFamily: fontFamilies.displayBold, fontSize: 13 },
    profilePillName: { fontFamily: fontFamilies.displaySemiBold, fontSize: 13, color: authColors.textPrimary },
    profileMenu: {
      position: 'absolute',
      top: 52,
      right: 0,
      width: 180,
      backgroundColor: authColors.cardBg,
      borderWidth: 1,
      borderColor: authColors.cardBorder,
      borderRadius: 14,
      paddingVertical: 6,
      zIndex: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 10,
    },
    profileMenuItem: { paddingVertical: 10, paddingHorizontal: 16 },
    profileMenuItemText: { fontFamily: fontFamilies.displayRegular, fontSize: 13, color: authColors.textPrimary },
    profileMenuDanger: { color: authColors.danger },

    // Hero + progress row
    heroRow: {
      flexDirection: 'row',
      gap: 20,
      paddingHorizontal: 28,
      marginBottom: 28,
      alignItems: 'stretch',
    },
    heroRowNarrow: { flexDirection: 'column' },
    hero: {
      flex: 2,
      borderRadius: 28,
      overflow: 'hidden',
      minHeight: 320,
    },
    // `flex: 2/1` above sizes hero/progressCard as a share of the ROW's
    // width when side by side, and that row-stretch is also what gives
    // `hero` a definite height in wide mode (needed for the background
    // image to size itself — react-native-web's Image resolves its fill
    // against the parent's height, and falls back to the raw photo's
    // intrinsic pixel size if that parent has no definite height, blowing
    // the banner up and making it overlay the next section instead of
    // pushing it down). Once heroRowNarrow stacks things into a column,
    // nothing gives `hero` a definite height any more, so it needs an
    // explicit one here instead of just resetting flex.
    heroNarrow: { flex: 0, height: 380 },
    heroOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
    heroContent: { flex: 1, padding: 28, justifyContent: 'center' },
    // Mirrors the reasoning above: centering via flex:1 only makes sense
    // once wide-mode row-stretch gives `hero` a real height to center
    // within. Stacked, content just flows top-down inside the fixed height.
    heroContentNarrow: { flex: 0, justifyContent: 'flex-start', paddingVertical: 24 },
    heroTag: {
      alignSelf: 'flex-start',
      backgroundColor: 'rgba(13, 25, 48, 0.65)',
      borderWidth: 1,
      borderColor: authColors.cardBorder,
      borderRadius: 999,
      paddingVertical: 6,
      paddingHorizontal: 14,
      marginBottom: 18,
    },
    heroTagText: { fontFamily: fontFamilies.displaySemiBold, fontSize: 12, color: authColors.textPrimary },
    heroTitle: { fontFamily: fontFamilies.displayExtraBold, fontSize: 34, color: '#FFFFFF' },
    heroTitleNarrow: { fontSize: 24 },
    heroSubtitle: { fontFamily: fontFamilies.displayRegular, fontSize: 16, color: 'rgba(255,255,255,0.85)', marginTop: 4 },
    heroQuote: { fontFamily: fontFamilies.script, fontSize: 24, color: authColors.accentCyan, marginTop: 20 },
    heroQuoteAttribution: { fontFamily: fontFamilies.displayRegular, fontSize: 12, color: 'rgba(255,255,255,0.65)', marginTop: 4 },
    heroButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      alignSelf: 'flex-start',
      borderRadius: 16,
      paddingVertical: 15,
      paddingHorizontal: 24,
      marginTop: 24,
      shadowColor: authColors.accentCyan,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
      elevation: 6,
    },
    heroButtonText: { fontFamily: fontFamilies.displayBold, fontSize: 15, color: '#FFFFFF', letterSpacing: 0.3 },
    heroCorner: { position: 'absolute', bottom: 20, right: 24, alignItems: 'flex-end' },
    heroCornerText: { fontFamily: fontFamilies.script, fontSize: 20, color: '#FFFFFF' },

    progressCard: {
      flex: 1,
      minWidth: 260,
      backgroundColor: authColors.cardBg,
      borderWidth: 1,
      borderColor: authColors.cardBorder,
      borderRadius: 24,
      padding: 24,
      justifyContent: 'space-between',
    },
    progressCardNarrow: { flex: 0 },
    progressHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    progressTitle: { fontFamily: fontFamilies.displayBold, fontSize: 16, color: authColors.textPrimary },
    progressLink: { fontFamily: fontFamilies.displaySemiBold, fontSize: 12, color: authColors.accentCyan },
    progressLevelRow: { flexDirection: 'row', alignItems: 'center', gap: 14, marginTop: 16 },
    progressLevelBadge: {
      width: 52,
      height: 52,
      borderRadius: 16,
      backgroundColor: 'rgba(56, 189, 248, 0.15)',
      borderWidth: 1,
      borderColor: authColors.accentCyan,
      alignItems: 'center',
      justifyContent: 'center',
    },
    progressLevelBadgeText: { fontFamily: fontFamilies.displayExtraBold, fontSize: 16, color: authColors.accentCyan },
    progressLevelLabel: { fontFamily: fontFamilies.displaySemiBold, fontSize: 13, color: authColors.textSecondary },
    progressBarTrack: {
      height: 10,
      borderRadius: 5,
      backgroundColor: authColors.inputBg,
      overflow: 'hidden',
      marginTop: 16,
    },
    progressBarFill: { height: '100%', borderRadius: 5, backgroundColor: authColors.accentCyan },
    progressBarLabel: { fontFamily: fontFamilies.displayRegular, fontSize: 12, color: authColors.textSecondary, marginTop: 8 },
    progressStatsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20 },
    progressStatItem: { alignItems: 'center' },
    progressStatValue: { fontFamily: fontFamilies.displayBold, fontSize: 15, color: authColors.textPrimary },
    progressStatLabel: { fontFamily: fontFamilies.displayRegular, fontSize: 10, color: authColors.textSecondary, marginTop: 2 },
    progressQuoteBox: {
      marginTop: 20,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: authColors.divider,
    },
    progressQuoteText: { fontFamily: fontFamilies.displaySemiBold, fontSize: 13, color: authColors.textPrimary, fontStyle: 'italic', lineHeight: 18 },
    progressQuoteAttribution: { fontFamily: fontFamilies.displayRegular, fontSize: 11, color: authColors.textSecondary, marginTop: 6 },

    // Sections
    section: { paddingHorizontal: 28, marginBottom: 28 },
    sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
    sectionTitle: { fontFamily: fontFamilies.displayBold, fontSize: 19, color: authColors.textPrimary },
    sectionLink: { fontFamily: fontFamilies.displaySemiBold, fontSize: 13, color: authColors.accentCyan },

    moduleCarousel: { gap: 14, paddingRight: 14 },
    moduleCard: {
      width: 184,
      backgroundColor: authColors.cardBg,
      borderWidth: 1,
      borderColor: authColors.cardBorder,
      borderRadius: 20,
      padding: 18,
    },
    moduleCardActive: {
      borderColor: authColors.accentCyan,
      shadowColor: authColors.accentCyan,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 6,
    },
    moduleIconBadge: {
      width: 48,
      height: 48,
      borderRadius: 14,
      backgroundColor: 'rgba(56, 189, 248, 0.14)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    moduleIconBadgeActive: { backgroundColor: authColors.accentCyan },
    moduleTitle: { fontFamily: fontFamilies.displayBold, fontSize: 14, color: authColors.textPrimary },
    moduleProgressTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: authColors.inputBg,
      overflow: 'hidden',
      marginTop: 10,
    },
    moduleProgressFill: { height: '100%', borderRadius: 3, backgroundColor: authColors.accentCyan },
    moduleCount: { fontFamily: fontFamilies.displayRegular, fontSize: 11, color: authColors.textSecondary, marginTop: 8 },
    moduleButton: {
      marginTop: 14,
      borderRadius: 12,
      paddingVertical: 10,
      alignItems: 'center',
    },
    moduleButtonActive: { backgroundColor: authColors.accentBlue },
    moduleButtonInactive: { backgroundColor: authColors.inputBg, borderWidth: 1, borderColor: authColors.inputBorder },
    moduleButtonText: { fontFamily: fontFamilies.displaySemiBold, fontSize: 12 },
    moduleButtonTextActive: { color: '#FFFFFF' },
    moduleButtonTextInactive: { color: authColors.textSecondary },

    journeyScroll: { paddingVertical: 8, paddingRight: 20 },
    journeyRow: { flexDirection: 'row', alignItems: 'flex-start' },
    journeyNode: { alignItems: 'center', width: 88 },
    journeyCircle: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: authColors.inputBg,
      borderWidth: 2,
      borderColor: authColors.inputBorder,
    },
    journeyCircleActive: {
      backgroundColor: 'rgba(56, 189, 248, 0.2)',
      borderColor: authColors.accentCyan,
      shadowColor: authColors.accentCyan,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.6,
      shadowRadius: 14,
      elevation: 6,
    },
    journeyCircleDone: {
      backgroundColor: authColors.accentBlue,
      borderColor: authColors.accentBlue,
    },
    journeyCircleText: { fontSize: 20 },
    journeyLabel: { fontFamily: fontFamilies.displayBold, fontSize: 12, color: authColors.textPrimary, marginTop: 8, textAlign: 'center' },
    journeyLabelLocked: { color: authColors.textMuted },
    journeySubLabel: { fontFamily: fontFamilies.displayRegular, fontSize: 10, color: authColors.textSecondary, textAlign: 'center' },
    journeyConnector: { width: 32, height: 2, backgroundColor: authColors.divider, marginTop: 27 },
    journeyConnectorDone: { backgroundColor: authColors.accentBlue },

    phraseCard: {
      borderRadius: 24,
      overflow: 'hidden',
      minHeight: 150,
    },
    phraseOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
    phraseContent: { padding: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flex: 1 },
    phraseTextWrap: { flex: 1 },
    phraseCardTitle: { fontFamily: fontFamilies.displaySemiBold, fontSize: 12, color: 'rgba(255,255,255,0.75)', marginBottom: 10 },
    phraseLu: { fontFamily: fontFamilies.displayBold, fontSize: 22, color: '#FFFFFF' },
    phrasePt: { fontFamily: fontFamilies.displayRegular, fontSize: 14, color: 'rgba(255,255,255,0.8)', marginTop: 6 },
    phraseAudioButton: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: 'rgba(255,255,255,0.15)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.35)',
      alignItems: 'center',
      justifyContent: 'center',
    },
  });
}
