import { Unit } from '../types/content';
import { a1Objectives } from './unitsA1Objectives';

export const units: Unit[] = [
  ...a1Objectives,
  {
    id: 'u3',
    title: 'Família e Dia a Dia',
    description: 'Vocabulário de família e do cotidiano',
    level: 'A1-INICIANTE',
    lessons: [
      {
        id: 'u3-l1',
        title: 'Família',
        exercises: [
          { type: 'multipleChoice', id: 'u3-l1-e1', promptLang: 'lu', prompt: 'de Papp', options: ['Pai', 'Mãe', 'Irmão', 'Avô'], correctIndex: 0, hint: "'Papp' é masculino, por isso leva o artigo 'de': 'de Papp' — uma forma carinhosa de 'pai', parecida com 'papai'." },
          { type: 'multipleChoice', id: 'u3-l1-e2', promptLang: 'lu', prompt: "d'Mamm", options: ['Pai', 'Mãe', 'Irmã', 'Avó'], correctIndex: 1, hint: "'Mamm' é feminino, por isso leva o artigo 'd'': 'd'Mamm' — semelhante a 'mamãe' e ao alemão 'Mama'." },
          { type: 'translate', id: 'u3-l1-e3', promptLang: 'pt', prompt: 'Irmão', acceptedAnswers: ['de Brudder', 'Brudder'], hint: "'Brudder' vem do alemão 'Bruder' (irmão) e é masculino: 'de Brudder'." },
          { type: 'translate', id: 'u3-l1-e4', promptLang: 'pt', prompt: 'Irmã', acceptedAnswers: ["d'Schwëster", 'Schwëster'], hint: "'Schwëster' vem do alemão 'Schwester' (irmã) e é feminino: 'd'Schwëster'." },
          { type: 'multipleChoice', id: 'u3-l1-e5', promptLang: 'lu', prompt: 'de Grousspapp', options: ['Avô', 'Avó', 'Pai', 'Filho'], correctIndex: 0, hint: "'Grouss' (grande) + 'Papp' (pai), literalmente 'pai grande' — ou seja, avô. É masculino: 'de Grousspapp'." },
          { type: 'match', id: 'u3-l1-e6', pairs: [
            { pt: 'Família', lu: "d'Famill", hint: "Vem do francês 'famille' e é feminino." },
            { pt: 'Filho', lu: "d'Kand", hint: "Vem do alemão 'Kind' e é neutro: 'd'Kand'." },
            { pt: 'Avó', lu: "d'Groussmamm", hint: "'Grouss' (grande) + 'Mamm' (mãe), feminino." },
            { pt: 'Pai', lu: 'de Papp', hint: "Forma carinhosa parecida com 'papai', masculino." },
          ] },
          { type: 'multipleChoice', id: 'u3-l1-e7', promptLang: 'pt', prompt: 'Avó', options: ["d'Groussmamm", 'de Grousspapp', "d'Mamm", "d'Schwëster"], correctIndex: 0, hint: "'Groussmamm' = 'mãe grande', ou seja, avó." },
          { type: 'translate', id: 'u3-l1-e8', promptLang: 'lu', prompt: "d'Famill", acceptedAnswers: ['Família', 'Familia'], hint: "'Famill' vem do francês 'famille', um dos muitos empréstimos franceses do luxemburguês. É feminino: 'd'Famill'." },
          { type: 'orderWords', id: 'u3-l1-e9', translation: 'Minha mãe é boa', words: ['Meng', 'Mamm', 'ass', 'gutt'], correctOrder: ['Meng', 'Mamm', 'ass', 'gutt'], hint: "'Meng' (minha) vem antes do substantivo, igual em português.", itemIds: ['word:mamm'] },
        ],
      },
      {
        id: 'u3-l2',
        title: 'Dia a dia',
        exercises: [
          { type: 'multipleChoice', id: 'u3-l2-e1', promptLang: 'lu', prompt: 'Haut', options: ['Hoje', 'Amanhã', 'Ontem', 'Agora'], correctIndex: 0, hint: "'Haut' vem do alemão 'heute' (hoje)." },
          { type: 'multipleChoice', id: 'u3-l2-e2', promptLang: 'lu', prompt: 'Muer', options: ['Ontem', 'Hoje', 'Amanhã', 'Sempre'], correctIndex: 2, hint: "'Muer' é parecido com 'Morgen', que em alemão pode significar 'manhã' ou 'amanhã'." },
          { type: 'translate', id: 'u3-l2-e3', promptLang: 'pt', prompt: 'Ontem', acceptedAnswers: ['Gëschter'], hint: "'Gëschter' vem do alemão 'gestern' (ontem)." },
          { type: 'multipleChoice', id: 'u3-l2-e4', promptLang: 'lu', prompt: "Wat ass d'Auer?", options: ['Que horas são?', 'Onde você mora?', 'Como vai?', 'Qual é seu nome?'], correctIndex: 0, hint: "Literalmente 'o que é o relógio?' — 'Auer' vem do francês 'heure' (hora)." },
          { type: 'translate', id: 'u3-l2-e5', promptLang: 'lu', prompt: 'Ech ginn schaffen', acceptedAnswers: ['Eu vou trabalhar'], hint: "'schaffen' significa 'trabalhar', vindo do alemão 'schaffen' (realizar/trabalhar)." },
          { type: 'translate', id: 'u3-l2-e6', promptLang: 'lu', prompt: 'Ech ginn heem', acceptedAnswers: ['Eu vou pra casa', 'Eu vou para casa'], hint: "'heem' é parecido com o alemão 'heim' (lar)." },
          { type: 'match', id: 'u3-l2-e7', pairs: [
            { pt: 'Hoje', lu: 'Haut', hint: "Vem do alemão 'heute'." },
            { pt: 'Amanhã', lu: 'Muer', hint: "Parecido com 'Morgen' em alemão." },
            { pt: 'Ontem', lu: 'Gëschter', hint: "Vem do alemão 'gestern'." },
            { pt: 'Que horas são?', lu: "Wat ass d'Auer?", hint: "Literalmente 'o que é o relógio?'." },
          ] },
          { type: 'multipleChoice', id: 'u3-l2-e8', promptLang: 'pt', prompt: 'Eu vou trabalhar', options: ['Ech ginn schaffen', 'Ech ginn heem', "Wat ass d'Auer?", 'Ech heeschen'], correctIndex: 0, hint: "'schaffen' = trabalhar." },
          { type: 'orderWords', id: 'u3-l2-e9', translation: 'Eu vou trabalhar hoje', words: ['Ech', 'ginn', 'haut', 'schaffen'], correctOrder: ['Ech', 'ginn', 'haut', 'schaffen'], hint: "'haut' (hoje) fica entre o verbo 'ginn' e 'schaffen'." },
        ],
      },
    ],
  },
  {
    id: 'u4',
    title: 'Comida e Bebida',
    description: 'Vocabulário essencial para comer e beber',
    level: 'A1-INICIANTE',
    lessons: [
      {
        id: 'u4-l1',
        title: 'No restaurante',
        exercises: [
          { type: 'multipleChoice', id: 'u4-l1-e1', promptLang: 'lu', prompt: "d'Brout", options: ['Pão', 'Água', 'Carne', 'Queijo'], correctIndex: 0, hint: "'Brout' vem do alemão 'Brot' (pão) e é neutro: 'd'Brout'." },
          { type: 'multipleChoice', id: 'u4-l1-e2', promptLang: 'lu', prompt: "d'Waasser", options: ['Vinho', 'Água', 'Suco', 'Leite'], correctIndex: 1, hint: "'Waasser' é a forma luxemburguesa de 'Wasser' (água) em alemão, e é neutro: 'd'Waasser'." },
          { type: 'translate', id: 'u4-l1-e3', promptLang: 'pt', prompt: 'Café', acceptedAnswers: ['de Kaffi', 'Kaffi'], hint: "'Kaffi' é parecido com o alemão 'Kaffee' e o inglês 'coffee', e é masculino: 'de Kaffi'." },
          { type: 'translate', id: 'u4-l1-e4', promptLang: 'pt', prompt: 'Carne', acceptedAnswers: ["d'Fleesch", 'Fleesch'], hint: "'Fleesch' vem do alemão 'Fleisch' (carne) e é neutro: 'd'Fleesch'." },
          { type: 'multipleChoice', id: 'u4-l1-e5', promptLang: 'lu', prompt: 'de Fësch', options: ['Peixe', 'Fruta', 'Legume', 'Sobremesa'], correctIndex: 0, hint: "'Fësch' vem do alemão 'Fisch' (peixe) e é masculino: 'de Fësch'." },
          { type: 'match', id: 'u4-l1-e6', pairs: [
            { pt: 'Pão', lu: "d'Brout", hint: "Vem do alemão 'Brot', neutro." },
            { pt: 'Água', lu: "d'Waasser", hint: "Vem do alemão 'Wasser', neutro." },
            { pt: 'Café', lu: 'de Kaffi', hint: "Parecido com o alemão 'Kaffee', masculino." },
            { pt: 'Carne', lu: "d'Fleesch", hint: "Vem do alemão 'Fleisch', neutro." },
          ] },
          { type: 'multipleChoice', id: 'u4-l1-e7', promptLang: 'pt', prompt: 'Chá', options: ['den Téi', 'de Kaffi', "d'Waasser", 'de Wäin'], correctIndex: 0, hint: "'Téi' é emprestado do francês/inglês 'thé/tea' e é masculino: 'den Téi'." },
          { type: 'translate', id: 'u4-l1-e8', promptLang: 'lu', prompt: 'lecker', acceptedAnswers: ['Delicioso', 'Gostoso', 'delicioso', 'gostoso'], hint: "'lecker' é igual ao alemão, usado para dizer que algo está gostoso." },
          { type: 'orderWords', id: 'u4-l1-e9', translation: 'O café está quente', words: ['De', 'Kaffi', 'ass', 'waarm'], correctOrder: ['De', 'Kaffi', 'ass', 'waarm'], hint: "'waarm' (quente) vem depois de 'ass' (está), no final da frase.", itemIds: ['word:kaffi'] },
        ],
      },
      {
        id: 'u4-l2',
        title: 'Frutas e legumes',
        exercises: [
          { type: 'multipleChoice', id: 'u4-l2-e1', promptLang: 'lu', prompt: "d'Uebst", options: ['Fruta', 'Legume', 'Doce', 'Bebida'], correctIndex: 0, hint: "'Uebst' vem do alemão 'Obst' (fruta) e é neutro: 'd'Uebst'." },
          { type: 'multipleChoice', id: 'u4-l2-e2', promptLang: 'lu', prompt: "d'Geméis", options: ['Fruta', 'Legume', 'Pão', 'Carne'], correctIndex: 1, hint: "'Geméis' vem do alemão 'Gemüse' (legumes/verduras) e é neutro: 'd'Geméis'." },
          { type: 'translate', id: 'u4-l2-e3', promptLang: 'pt', prompt: 'Açúcar', acceptedAnswers: ['de Zocker', 'Zocker'], hint: "'Zocker' vem do alemão 'Zucker' (açúcar) e é masculino: 'de Zocker'." },
          { type: 'translate', id: 'u4-l2-e4', promptLang: 'pt', prompt: 'Sal', acceptedAnswers: ["d'Salz", 'Salz'], hint: "'Salz' é escrito quase igual ao alemão 'Salz' (sal) e é neutro: 'd'Salz'." },
          { type: 'multipleChoice', id: 'u4-l2-e5', promptLang: 'lu', prompt: 'Ech hu Honger', options: ['Estou com fome', 'Estou com sede', 'Estou cansado', 'Estou feliz'], correctIndex: 0, hint: "'Honger' vem do alemão 'Hunger' (fome)." },
          { type: 'match', id: 'u4-l2-e6', pairs: [
            { pt: 'Fruta', lu: "d'Uebst", hint: "Vem do alemão 'Obst', neutro." },
            { pt: 'Legume', lu: "d'Geméis", hint: "Vem do alemão 'Gemüse', neutro." },
            { pt: 'Açúcar', lu: 'de Zocker', hint: "Vem do alemão 'Zucker', masculino." },
            { pt: 'Sal', lu: "d'Salz", hint: "Escrito quase igual ao alemão, neutro." },
          ] },
          { type: 'multipleChoice', id: 'u4-l2-e7', promptLang: 'pt', prompt: 'Estou com sede', options: ['Ech hu Duuscht', 'Ech hu Honger', 'Ech si midd', 'Ech si frou'], correctIndex: 0, hint: "'Duuscht' vem do alemão 'Durst' (sede)." },
          { type: 'translate', id: 'u4-l2-e8', promptLang: 'lu', prompt: 'Iessen', acceptedAnswers: ['Comida', 'Comer', 'comida', 'comer'], hint: "'Iessen' vem do alemão 'essen' (comer), usado tanto como verbo quanto substantivo." },
          { type: 'orderWords', id: 'u4-l2-e9', translation: 'A fruta é saudável', words: ["D'Uebst", 'ass', 'gesond'], correctOrder: ["D'Uebst", 'ass', 'gesond'], hint: "'gesond' (saudável) vem depois de 'ass' (é), como em português.", itemIds: ['word:uebst'] },
        ],
      },
    ],
  },
  {
    id: 'u5',
    title: 'Compras',
    description: 'Comprar, pagar e negociar preços',
    level: 'A2-INICIANTE',
    lessons: [
      {
        id: 'u5-l1',
        title: 'Na loja',
        exercises: [
          { type: 'multipleChoice', id: 'u5-l1-e1', promptLang: 'lu', prompt: "d'Geschäft", options: ['Loja', 'Banco', 'Escola', 'Hospital'], correctIndex: 0, hint: "'Geschäft' vem do alemão 'Geschäft' (negócio/loja) e é neutro: 'd'Geschäft'." },
          { type: 'multipleChoice', id: 'u5-l1-e2', promptLang: 'lu', prompt: 'kafen', options: ['Vender', 'Comprar', 'Pagar', 'Trocar'], correctIndex: 1, hint: "'kafen' é parecido com o alemão 'kaufen' (comprar)." },
          { type: 'translate', id: 'u5-l1-e3', promptLang: 'pt', prompt: 'Dinheiro', acceptedAnswers: ["d'Suen", 'Suen'], hint: "'Suen' (sempre no plural) é a palavra do luxemburguês para dinheiro: 'd'Suen'." },
          { type: 'translate', id: 'u5-l1-e4', promptLang: 'pt', prompt: 'Preço', acceptedAnswers: ['de Präis', 'Präis'], hint: "'Präis' vem do francês 'prix' (preço) e é masculino: 'de Präis'." },
          { type: 'multipleChoice', id: 'u5-l1-e5', promptLang: 'lu', prompt: 'Wéi vill kascht dat?', options: ['Quanto custa isso?', 'Onde fica isso?', 'O que é isso?', 'Quando abre?'], correctIndex: 0, hint: "'kascht' vem de 'kosten' (custar); a frase pergunta literalmente 'quanto custa isso?'." },
          { type: 'match', id: 'u5-l1-e6', pairs: [
            { pt: 'Loja', lu: "d'Geschäft", hint: "Vem do alemão 'Geschäft', neutro." },
            { pt: 'Comprar', lu: 'kafen', hint: "Parecido com o alemão 'kaufen'." },
            { pt: 'Dinheiro', lu: "d'Suen", hint: "Palavra própria do luxemburguês, sempre no plural." },
            { pt: 'Preço', lu: 'de Präis', hint: "Vem do francês 'prix', masculino." },
          ] },
          { type: 'multipleChoice', id: 'u5-l1-e7', promptLang: 'pt', prompt: 'Pagar', options: ['bezuelen', 'kafen', 'verkeeafen', 'siche'], correctIndex: 0, hint: "'bezuelen' vem do alemão 'bezahlen' (pagar)." },
          { type: 'translate', id: 'u5-l1-e8', promptLang: 'lu', prompt: "d'Rechnung", acceptedAnswers: ['A conta', 'a conta'], hint: "'Rechnung' vem do alemão 'Rechnung' (conta/fatura)." },
          { type: 'orderWords', id: 'u5-l1-e9', translation: 'Eu compro pão', words: ['Ech', 'kafen', 'Brout'], correctOrder: ['Ech', 'kafen', 'Brout'], hint: "'kafen' (comprar) vem logo depois do sujeito 'Ech' (eu)." },
        ],
      },
      {
        id: 'u5-l2',
        title: 'Preços',
        exercises: [
          { type: 'multipleChoice', id: 'u5-l2-e1', promptLang: 'lu', prompt: 'deier', options: ['Caro', 'Barato', 'Grátis', 'Novo'], correctIndex: 0, hint: "'deier' vem do alemão 'teuer' (caro)." },
          { type: 'multipleChoice', id: 'u5-l2-e2', promptLang: 'lu', prompt: 'bëlleg', options: ['Caro', 'Barato', 'Usado', 'Pequeno'], correctIndex: 1, hint: "'bëlleg' vem do alemão 'billig' (barato)." },
          { type: 'translate', id: 'u5-l2-e3', promptLang: 'pt', prompt: 'Grátis', acceptedAnswers: ['Gratis', 'gratis'], hint: "'Gratis' é praticamente igual em várias línguas, incluindo o português." },
          { type: 'multipleChoice', id: 'u5-l2-e4', promptLang: 'lu', prompt: 'Kann ech Iech hëllefen?', options: ['Posso ajudá-lo?', 'Você pode me ajudar?', 'Está aberto?', 'Quanto custa?'], correctIndex: 0, hint: "'hëllefen' vem do alemão 'helfen' (ajudar); frase típica de atendimento em lojas." },
          { type: 'translate', id: 'u5-l2-e5', promptLang: 'lu', prompt: 'Ech géif gär dëst kafen', acceptedAnswers: ['Eu gostaria de comprar isso'], hint: "'géif gär' expressa 'gostaria', uma forma educada e comum em pedidos." },
          { type: 'match', id: 'u5-l2-e6', pairs: [
            { pt: 'Caro', lu: 'deier', hint: "Vem do alemão 'teuer'." },
            { pt: 'Barato', lu: 'bëlleg', hint: "Vem do alemão 'billig'." },
            { pt: 'A conta', lu: "d'Rechnung", hint: "Vem do alemão 'Rechnung'." },
            { pt: 'Pagar', lu: 'bezuelen', hint: "Vem do alemão 'bezahlen'." },
          ] },
          { type: 'multipleChoice', id: 'u5-l2-e7', promptLang: 'pt', prompt: 'Quanto custa isso?', options: ['Wéi vill kascht dat?', 'Wou ass dat?', 'Wat ass dat?', 'Wéini mécht et op?'], correctIndex: 0, hint: "'kascht' vem de 'kosten' (custar)." },
          { type: 'translate', id: 'u5-l2-e8', promptLang: 'lu', prompt: 'Gutt Präis', acceptedAnswers: ['Bom preço'], hint: "'Gutt' (bom) vem do alemão 'gut'; 'Präis' (preço) vem do francês 'prix'." },
          { type: 'orderWords', id: 'u5-l2-e9', translation: 'O preço está bom', words: ['De', 'Präis', 'ass', 'gutt'], correctOrder: ['De', 'Präis', 'ass', 'gutt'], hint: "'gutt' (bom) vem depois de 'ass' (está), no final.", itemIds: ['word:präis'] },
        ],
      },
    ],
  },
  {
    id: 'u6',
    title: 'Viagens',
    description: 'Se locomover e viajar em luxemburguês',
    level: 'A2-INICIANTE',
    lessons: [
      {
        id: 'u6-l1',
        title: 'Transporte',
        exercises: [
          { type: 'multipleChoice', id: 'u6-l1-e1', promptLang: 'lu', prompt: 'de Zuch', options: ['Trem', 'Ônibus', 'Avião', 'Carro'], correctIndex: 0, hint: "'Zuch' vem do alemão 'Zug' (trem) e é masculino: 'de Zuch'." },
          { type: 'multipleChoice', id: 'u6-l1-e2', promptLang: 'lu', prompt: 'de Fliger', options: ['Trem', 'Barco', 'Avião', 'Bicicleta'], correctIndex: 2, hint: "'Fliger' vem de 'fléien' (voar), parecido com o alemão 'Flieger', e é masculino: 'de Fliger'." },
          { type: 'translate', id: 'u6-l1-e3', promptLang: 'pt', prompt: 'Ônibus', acceptedAnswers: ['de Bus', 'Bus'], hint: "'Bus' é emprestado do inglês/francês, igual em várias línguas, e é masculino: 'de Bus'." },
          { type: 'translate', id: 'u6-l1-e4', promptLang: 'pt', prompt: 'Carro', acceptedAnswers: ['den Auto', 'Auto'], hint: "'Auto' é uma forma curta internacional de 'automóvel', usada também em alemão, e é masculino: 'den Auto'." },
          { type: 'multipleChoice', id: 'u6-l1-e5', promptLang: 'lu', prompt: "Wou ass d'Gare?", options: ['Onde fica a estação?', 'Que horas parte?', 'Quanto custa?', 'É longe?'], correctIndex: 0, hint: "'Gare' vem do francês (estação); pergunta comum para achar a estação de trem." },
          { type: 'match', id: 'u6-l1-e6', pairs: [
            { pt: 'Trem', lu: 'de Zuch', hint: "Vem do alemão 'Zug', masculino." },
            { pt: 'Avião', lu: 'de Fliger', hint: "Vem de 'fléien' (voar), masculino." },
            { pt: 'Ônibus', lu: 'de Bus', hint: "Palavra internacional, masculino." },
            { pt: 'Carro', lu: 'den Auto', hint: "Forma curta de 'automóvel', masculino." },
          ] },
          { type: 'multipleChoice', id: 'u6-l1-e7', promptLang: 'pt', prompt: 'Viajar', options: ['reesen', 'schaffen', 'kafen', 'schwammen'], correctIndex: 0, hint: "'reesen' vem do alemão 'reisen' (viajar)." },
          { type: 'translate', id: 'u6-l1-e8', promptLang: 'lu', prompt: 'ukommen', acceptedAnswers: ['Chegar', 'chegar'], hint: "'ukommen' vem do alemão 'ankommen' (chegar)." },
        ],
      },
      {
        id: 'u6-l2',
        title: 'Na viagem',
        exercises: [
          { type: 'multipleChoice', id: 'u6-l2-e1', promptLang: 'lu', prompt: "d'Vakanz", options: ['Férias', 'Trabalho', 'Reunião', 'Escola'], correctIndex: 0, hint: "'Vakanz' vem do francês 'vacance' (férias) e é feminino: 'd'Vakanz'." },
          { type: 'multipleChoice', id: 'u6-l2-e2', promptLang: 'lu', prompt: 'den Hotel', options: ['Restaurante', 'Hotel', 'Loja', 'Escola'], correctIndex: 1, hint: "'Hotel' é praticamente igual em várias línguas europeias, e é masculino: 'den Hotel'." },
          { type: 'translate', id: 'u6-l2-e3', promptLang: 'pt', prompt: 'Passaporte', acceptedAnswers: ['de Pass', 'Pass'], hint: "'Pass' é uma forma curta comum em alemão para 'Reisepass' (passaporte), e é masculino: 'de Pass'." },
          { type: 'multipleChoice', id: 'u6-l2-e4', promptLang: 'lu', prompt: 'Wou ass...?', options: ['Onde é...?', 'O que é...?', 'Quando é...?', 'Quem é...?'], correctIndex: 0, hint: "'Wou' vem do alemão 'wo' (onde)." },
          { type: 'translate', id: 'u6-l2-e5', promptLang: 'lu', prompt: 'ofreesen', acceptedAnswers: ['Partir', 'partir'], hint: "'of-' é um prefixo que indica afastamento; 'reesen' é viajar — juntos, 'partir'." },
          { type: 'match', id: 'u6-l2-e6', pairs: [
            { pt: 'Férias', lu: "d'Vakanz", hint: "Vem do francês 'vacance', feminino." },
            { pt: 'Hotel', lu: 'den Hotel', hint: "Palavra internacional, masculino." },
            { pt: 'Passaporte', lu: 'de Pass', hint: "Forma curta de 'Reisepass', masculino." },
            { pt: 'Chegar', lu: 'ukommen', hint: "Vem do alemão 'ankommen'." },
          ] },
          { type: 'multipleChoice', id: 'u6-l2-e7', promptLang: 'pt', prompt: 'Partir', options: ['ofreesen', 'ukommen', 'reesen', 'bleiwen'], correctIndex: 0, hint: "'of-' (afastamento) + 'reesen' (viajar)." },
          { type: 'translate', id: 'u6-l2-e8', promptLang: 'lu', prompt: "d'Kaart", acceptedAnswers: ['O mapa', 'O bilhete', 'o mapa', 'o bilhete'], hint: "'Kaart' vem do francês 'carte', usada tanto para 'mapa' quanto 'bilhete/cartão'." },
        ],
      },
    ],
  },
  {
    id: 'u12',
    title: 'Escola e Estudos',
    description: 'Vocabulário do ambiente escolar e universitário',
    level: 'A2-INICIANTE',
    lessons: [
      {
        id: 'u12-l1',
        title: 'Na escola',
        exercises: [
          { type: 'multipleChoice', id: 'u12-l1-e1', promptLang: 'lu', prompt: "d'Schoul", options: ['Escola', 'Casa', 'Loja', 'Hospital'], correctIndex: 0, hint: "'Schoul' vem do alemão 'Schule' (escola) e é feminino: 'd'Schoul'." },
          { type: 'multipleChoice', id: 'u12-l1-e2', promptLang: 'lu', prompt: "d'Buch", options: ['Livro', 'Caderno', 'Caneta', 'Mesa'], correctIndex: 0, hint: "'Buch' vem do alemão 'Buch' (livro) e é neutro: 'd'Buch'." },
          { type: 'translate', id: 'u12-l1-e3', promptLang: 'pt', prompt: 'Aluno', acceptedAnswers: ['de Schüler', 'Schüler'], hint: "'Schüler' vem do alemão 'Schüler' (aluno) e é masculino: 'de Schüler'." },
          { type: 'translate', id: 'u12-l1-e4', promptLang: 'pt', prompt: 'Prova', acceptedAnswers: ["d'Prüfung", 'Prüfung'], hint: "'Prüfung' vem do alemão 'Prüfung' (prova/exame) e é feminino: 'd'Prüfung'." },
          { type: 'fillBlank', id: 'u12-l1-e5', promptLang: 'lu', sentence: 'Ech ___ all Dag an der Schoul', translation: 'Eu estudo todo dia na escola', options: ['léieren', 'iessen', 'schlofen', 'kafen'], correctAnswer: 'léieren', hint: "'léieren' vem do alemão 'lernen' (aprender/estudar)." },
          { type: 'match', id: 'u12-l1-e6', pairs: [
            { pt: 'Escola', lu: "d'Schoul", hint: "Vem do alemão 'Schule', feminino." },
            { pt: 'Livro', lu: "d'Buch", hint: "Vem do alemão 'Buch', neutro." },
            { pt: 'Aluno', lu: 'de Schüler', hint: "Vem do alemão 'Schüler', masculino." },
            { pt: 'Prova', lu: "d'Prüfung", hint: "Vem do alemão 'Prüfung', feminino." },
          ] },
          { type: 'multipleChoice', id: 'u12-l1-e7', promptLang: 'pt', prompt: 'Dever de casa', options: ["d'Hausaufgab", "d'Prüfung", "d'Buch", 'de Schüler'], correctIndex: 0, hint: "'Haus' (casa) + 'Aufgab' (tarefa) = 'dever de casa', feminino: 'd'Hausaufgab'." },
          { type: 'translate', id: 'u12-l1-e8', promptLang: 'lu', prompt: "d'Universitéit", acceptedAnswers: ['Universidade'], hint: "'Universitéit' vem do francês 'université' e é feminino: 'd'Universitéit'." },
        ],
      },
      {
        id: 'u12-l2',
        title: 'Estudando',
        exercises: [
          { type: 'multipleChoice', id: 'u12-l2-e1', promptLang: 'lu', prompt: 'de Cours', options: ['Curso', 'Prova', 'Turma', 'Diploma'], correctIndex: 0, hint: "'Cours' vem do francês 'cours' (curso) — essa é a grafia oficial em luxemburguês, não 'Kurs'. É masculino: 'de Cours'." },
          { type: 'multipleChoice', id: 'u12-l2-e2', promptLang: 'lu', prompt: "d'Bibliothéik", options: ['Escola', 'Biblioteca', 'Sala', 'Livraria'], correctIndex: 1, hint: "'Bibliothéik' vem do francês 'bibliothèque' (biblioteca) e é feminino: 'd'Bibliothéik'." },
          { type: 'translate', id: 'u12-l2-e3', promptLang: 'pt', prompt: 'Diploma', acceptedAnswers: ['den Diplom', 'Diplom'], hint: "'Diplom' é praticamente igual ao alemão 'Diplom' e é masculino: 'den Diplom'." },
          { type: 'translate', id: 'u12-l2-e4', promptLang: 'pt', prompt: 'Bolsa de estudos', acceptedAnswers: ["d'Bourse", 'Bourse'], hint: "A palavra oficial em luxemburguês é 'Bourse' (do francês), não 'Stipendium'. É feminino: 'd'Bourse'.", wordGlosses: { bolsa: 'Bourse', estudos: 'Bourse' } },
          { type: 'fillBlank', id: 'u12-l2-e5', promptLang: 'lu', sentence: 'Si studéiert un der ___', translation: 'Ela estuda na universidade', options: ['Universitéit', 'Schoul', 'Büro', 'Spidol'], correctAnswer: 'Universitéit', hint: "'Universitéit' vem do francês 'université'." },
          { type: 'match', id: 'u12-l2-e6', pairs: [
            { pt: 'Curso', lu: 'de Cours', hint: "Grafia oficial (do francês 'cours'), masculino." },
            { pt: 'Biblioteca', lu: "d'Bibliothéik", hint: "Vem do francês 'bibliothèque', feminino." },
            { pt: 'Diploma', lu: 'den Diplom', hint: "Quase igual ao alemão 'Diplom', masculino." },
            { pt: 'Bolsa de estudos', lu: "d'Bourse", hint: "Vem do francês 'bourse', feminino." },
          ] },
          { type: 'multipleChoice', id: 'u12-l2-e7', promptLang: 'pt', prompt: 'Turma', options: ["d'Klass", 'de Cours', 'den Diplom', "d'Buch"], correctIndex: 0, hint: "'Klass' vem do alemão 'Klasse' (turma/classe) e é feminino: 'd'Klass'." },
          { type: 'fillBlank', id: 'u12-l2-e8', promptLang: 'lu', sentence: 'Mir hunn eng ___ haut Owend', translation: 'Nós temos uma prova hoje à noite', options: ['Prüfung', 'Buch', 'Cours', 'Diplom'], correctAnswer: 'Prüfung', hint: "'Prüfung' vem do alemão 'Prüfung' (prova)." },
        ],
      },
    ],
  },
  {
    id: 'u13',
    title: 'Clima e Estações',
    description: 'Falar sobre o tempo e as estações do ano',
    level: 'A2-INICIANTE',
    lessons: [
      {
        id: 'u13-l1',
        title: 'O tempo',
        exercises: [
          { type: 'multipleChoice', id: 'u13-l1-e1', promptLang: 'lu', prompt: "d'Sonn", options: ['Sol', 'Chuva', 'Neve', 'Vento'], correctIndex: 0, hint: "'Sonn' vem do alemão 'Sonne' (sol) e é feminino: 'd'Sonn'." },
          { type: 'multipleChoice', id: 'u13-l1-e2', promptLang: 'lu', prompt: 'de Reen', options: ['Sol', 'Chuva', 'Neve', 'Vento'], correctIndex: 1, hint: "'Reen' vem do alemão 'Regen' (chuva) e é masculino: 'de Reen'." },
          { type: 'translate', id: 'u13-l1-e3', promptLang: 'pt', prompt: 'Neve', acceptedAnswers: ['de Schnéi', 'Schnéi'], hint: "'Schnéi' vem do alemão 'Schnee' (neve) e é masculino: 'de Schnéi'." },
          { type: 'translate', id: 'u13-l1-e4', promptLang: 'pt', prompt: 'Vento', acceptedAnswers: ['de Wand', 'Wand'], hint: "'Wand' vem do alemão 'Wind' (vento) e é masculino: 'de Wand'." },
          { type: 'fillBlank', id: 'u13-l1-e5', promptLang: 'lu', sentence: 'Haut ass et ganz ___', translation: 'Hoje está muito quente', options: ['waarm', 'kal', 'nass', 'midd'], correctAnswer: 'waarm', hint: "'waarm' vem do alemão 'warm' (quente)." },
          { type: 'match', id: 'u13-l1-e6', pairs: [
            { pt: 'Sol', lu: "d'Sonn", hint: "Vem do alemão 'Sonne', feminino." },
            { pt: 'Chuva', lu: 'de Reen', hint: "Vem do alemão 'Regen', masculino." },
            { pt: 'Neve', lu: 'de Schnéi', hint: "Vem do alemão 'Schnee', masculino." },
            { pt: 'Vento', lu: 'de Wand', hint: "Vem do alemão 'Wind', masculino." },
          ] },
          { type: 'multipleChoice', id: 'u13-l1-e7', promptLang: 'pt', prompt: 'Frio', options: ['kal', 'waarm', 'nass', 'midd'], correctIndex: 0, hint: "'kal' vem do alemão 'kalt' (frio)." },
          { type: 'translate', id: 'u13-l1-e8', promptLang: 'lu', prompt: "d'Wieder", acceptedAnswers: ['Tempo', 'Clima', 'tempo', 'clima'], hint: "'Wieder' vem do alemão 'Wetter' (tempo/clima) e é neutro: 'd'Wieder'." },
        ],
      },
      {
        id: 'u13-l2',
        title: 'Estações do ano',
        exercises: [
          { type: 'multipleChoice', id: 'u13-l2-e1', promptLang: 'lu', prompt: "d'Fréijoer", options: ['Primavera', 'Verão', 'Outono', 'Inverno'], correctIndex: 0, hint: "'Fréi' (cedo) + 'Joer' (ano) — literalmente 'início do ano', ou seja, primavera. É neutro: 'd'Fréijoer'." },
          { type: 'multipleChoice', id: 'u13-l2-e2', promptLang: 'lu', prompt: 'de Summer', options: ['Primavera', 'Verão', 'Outono', 'Inverno'], correctIndex: 1, hint: "'Summer' vem do alemão 'Sommer' (verão) e é masculino: 'de Summer'." },
          { type: 'translate', id: 'u13-l2-e3', promptLang: 'pt', prompt: 'Outono', acceptedAnswers: ['den Hierscht', 'Hierscht'], hint: "'Hierscht' vem do alemão 'Herbst' (outono) e é masculino: 'den Hierscht'." },
          { type: 'translate', id: 'u13-l2-e4', promptLang: 'pt', prompt: 'Inverno', acceptedAnswers: ['de Wanter', 'Wanter'], hint: "'Wanter' vem do alemão 'Winter' (inverno) e é masculino: 'de Wanter'." },
          { type: 'fillBlank', id: 'u13-l2-e5', promptLang: 'lu', sentence: 'Am ___ ass et vill kal', translation: 'No inverno está muito frio', options: ['Wanter', 'Summer', 'Fréijoer', 'Hierscht'], correctAnswer: 'Wanter', hint: "'Wanter' significa inverno." },
          { type: 'match', id: 'u13-l2-e6', pairs: [
            { pt: 'Primavera', lu: "d'Fréijoer", hint: "Literalmente 'início do ano', neutro." },
            { pt: 'Verão', lu: 'de Summer', hint: "Vem do alemão 'Sommer', masculino." },
            { pt: 'Outono', lu: 'den Hierscht', hint: "Vem do alemão 'Herbst', masculino." },
            { pt: 'Inverno', lu: 'de Wanter', hint: "Vem do alemão 'Winter', masculino." },
          ] },
          { type: 'multipleChoice', id: 'u13-l2-e7', promptLang: 'pt', prompt: 'Verão', options: ['de Summer', 'de Wanter', 'den Hierscht', "d'Fréijoer"], correctIndex: 0, hint: "'Summer' vem do alemão 'Sommer', masculino." },
          { type: 'fillBlank', id: 'u13-l2-e8', promptLang: 'lu', sentence: 'Meng Liblingsjoreszäit ass de ___', translation: 'Minha estação favorita é o verão', options: ['Summer', 'Wanter', 'Reen', 'Wand'], correctAnswer: 'Summer', hint: "'Summer' significa verão." },
        ],
      },
    ],
  },
  {
    id: 'u7',
    title: 'Trabalho',
    description: 'Vocabulário do ambiente profissional',
    level: 'B1-INICIANTE',
    lessons: [
      {
        id: 'u7-l1',
        title: 'No escritório',
        exercises: [
          { type: 'multipleChoice', id: 'u7-l1-e1', promptLang: 'lu', prompt: "d'Aarbecht", options: ['Trabalho', 'Descanso', 'Escola', 'Casa'], correctIndex: 0, hint: "'Aarbecht' vem do alemão 'Arbeit' (trabalho) e é feminino: 'd'Aarbecht'." },
          { type: 'multipleChoice', id: 'u7-l1-e2', promptLang: 'lu', prompt: 'de Büro', options: ['Casa', 'Escritório', 'Loja', 'Fábrica'], correctIndex: 1, hint: "'Büro' vem do francês 'bureau' (escritório) e é masculino: 'de Büro'." },
          { type: 'translate', id: 'u7-l1-e3', promptLang: 'pt', prompt: 'Chefe', acceptedAnswers: ['de Chef', 'Chef'], hint: "'Chef' vem diretamente do francês (chefe) e é masculino: 'de Chef'." },
          { type: 'translate', id: 'u7-l1-e4', promptLang: 'pt', prompt: 'Colega', acceptedAnswers: ['de Kolleeg', 'Kolleeg'], hint: "'Kolleeg' (com dois 'e') vem do francês/latim 'collègue' (colega) e é masculino: 'de Kolleeg'." },
          { type: 'multipleChoice', id: 'u7-l1-e5', promptLang: 'lu', prompt: "d'Reunioun", options: ['Reunião', 'Feriado', 'Salário', 'Tarefa'], correctIndex: 0, hint: "'Reunioun' vem do francês 'réunion' (reunião) e é feminino: 'd'Reunioun'." },
          { type: 'match', id: 'u7-l1-e6', pairs: [
            { pt: 'Trabalho', lu: "d'Aarbecht", hint: "Vem do alemão 'Arbeit', feminino." },
            { pt: 'Escritório', lu: 'de Büro', hint: "Vem do francês 'bureau', masculino." },
            { pt: 'Chefe', lu: 'de Chef', hint: "Emprestado do francês, masculino." },
            { pt: 'Colega', lu: 'de Kolleeg', hint: "Vem do francês/latim 'collègue', masculino." },
          ] },
          { type: 'multipleChoice', id: 'u7-l1-e7', promptLang: 'pt', prompt: 'Trabalhar', options: ['schaffen', 'schwätzen', 'iessen', 'reesen'], correctIndex: 0, hint: "'schaffen' vem do alemão 'schaffen' (realizar/trabalhar)." },
          { type: 'translate', id: 'u7-l1-e8', promptLang: 'lu', prompt: "d'Aufgab", acceptedAnswers: ['A tarefa', 'a tarefa'], hint: "'Aufgab' vem do alemão 'Aufgabe' (tarefa)." },
        ],
      },
      {
        id: 'u7-l2',
        title: 'Rotina profissional',
        exercises: [
          { type: 'multipleChoice', id: 'u7-l2-e1', promptLang: 'lu', prompt: 'verdéngen', options: ['Ganhar', 'Gastar', 'Pedir', 'Perder'], correctIndex: 0, hint: "'verdéngen' vem do alemão 'verdienen' (ganhar/merecer)." },
          { type: 'translate', id: 'u7-l2-e2', promptLang: 'pt', prompt: 'Salário', acceptedAnswers: ['de Loun', 'Loun'], hint: "'Loun' vem do alemão 'Lohn' (salário)." },
          { type: 'multipleChoice', id: 'u7-l2-e3', promptLang: 'lu', prompt: 'Ech schaffen als Enseignant', options: ['Eu trabalho como professor', 'Eu estudo como professor', 'Eu quero ser professor', 'Eu conheço um professor'], correctIndex: 0, hint: "'Enseignant' é emprestado do francês (professor), mostrando a mistura franco-germânica do luxemburguês." },
          { type: 'translate', id: 'u7-l2-e4', promptLang: 'lu', prompt: 'Ech hu vill Aarbecht haut', acceptedAnswers: ['Eu tenho muito trabalho hoje'], hint: "Reaproveita 'Aarbecht' (trabalho) e 'haut' (hoje), já vistos antes." },
          { type: 'multipleChoice', id: 'u7-l2-e5', promptLang: 'pt', prompt: 'Reunião', options: ["d'Reunioun", "d'Aufgab", 'de Loun', 'de Kolleeg'], correctIndex: 0, hint: "'Reunioun' vem do francês 'réunion', feminino." },
          { type: 'match', id: 'u7-l2-e6', pairs: [
            { pt: 'Ganhar', lu: 'verdéngen', hint: "Vem do alemão 'verdienen'." },
            { pt: 'Salário', lu: 'de Loun', hint: "Vem do alemão 'Lohn'." },
            { pt: 'Reunião', lu: "d'Reunioun", hint: "Vem do francês 'réunion', feminino." },
            { pt: 'Tarefa', lu: "d'Aufgab", hint: "Vem do alemão 'Aufgabe'." },
          ] },
          { type: 'multipleChoice', id: 'u7-l2-e7', promptLang: 'lu', prompt: 'pünktlech', options: ['Pontual', 'Atrasado', 'Ocupado', 'Livre'], correctIndex: 0, hint: "'pünktlech' vem do alemão 'pünktlich' (pontual)." },
          { type: 'translate', id: 'u7-l2-e8', promptLang: 'pt', prompt: 'Ocupado', acceptedAnswers: ['besat'], hint: "'besat' vem do alemão 'besetzt' (ocupado)." },
        ],
      },
    ],
  },
  {
    id: 'u8',
    title: 'Saúde',
    description: 'Falar sobre corpo, sintomas e bem-estar',
    level: 'B1-INICIANTE',
    lessons: [
      {
        id: 'u8-l1',
        title: 'No médico',
        exercises: [
          { type: 'multipleChoice', id: 'u8-l1-e1', promptLang: 'lu', prompt: 'den Dokter', options: ['Médico', 'Professor', 'Motorista', 'Cozinheiro'], correctIndex: 0, hint: "'Dokter' é parecido com 'doutor', de origem latina comum a várias línguas. É masculino: 'den Dokter'." },
          { type: 'multipleChoice', id: 'u8-l1-e2', promptLang: 'lu', prompt: "d'Spidol", options: ['Escola', 'Hospital', 'Farmácia', 'Banco'], correctIndex: 1, hint: "'Spidol' vem do latim 'hospitale', a mesma raiz de 'hospital' em português. É neutro: 'd'Spidol'." },
          { type: 'translate', id: 'u8-l1-e3', promptLang: 'pt', prompt: 'Doente', acceptedAnswers: ['krank'], hint: "'krank' vem do alemão 'krank' (doente)." },
          { type: 'translate', id: 'u8-l1-e4', promptLang: 'pt', prompt: 'Saudável', acceptedAnswers: ['gesond'], hint: "'gesond' vem do alemão 'gesund' (saudável)." },
          { type: 'multipleChoice', id: 'u8-l1-e5', promptLang: 'lu', prompt: 'Ech hu Kappwéi', options: ['Eu tenho dor de cabeça', 'Eu estou cansado', 'Eu estou com fome', 'Eu estou feliz'], correctIndex: 0, hint: "'Kapp' (cabeça) + 'wéi' (dor) — literalmente 'dor de cabeça'." },
          { type: 'match', id: 'u8-l1-e6', pairs: [
            { pt: 'Médico', lu: 'den Dokter', hint: "Origem latina, como 'doutor', masculino." },
            { pt: 'Hospital', lu: "d'Spidol", hint: "Vem do latim 'hospitale', neutro." },
            { pt: 'Doente', lu: 'krank', hint: "Vem do alemão 'krank'." },
            { pt: 'Saudável', lu: 'gesond', hint: "Vem do alemão 'gesund'." },
          ] },
          { type: 'multipleChoice', id: 'u8-l1-e7', promptLang: 'pt', prompt: 'Farmácia', options: ["d'Apdikt", "d'Spidol", 'de Büro', "d'Geschäft"], correctIndex: 0, hint: "'Apdikt' vem do alemão 'Apotheke' (farmácia) e é feminino: 'd'Apdikt'." },
          { type: 'translate', id: 'u8-l1-e8', promptLang: 'lu', prompt: "d'Féiwer", acceptedAnswers: ['Febre', 'febre'], hint: "A grafia oficial é 'Féiwer' (não 'Fieber'), vindo do alemão 'Fieber' (febre)." },
        ],
      },
      {
        id: 'u8-l2',
        title: 'Sintomas',
        exercises: [
          { type: 'multipleChoice', id: 'u8-l2-e1', promptLang: 'lu', prompt: 'sech ausrouen', options: ['Descansar', 'Correr', 'Trabalhar', 'Cozinhar'], correctIndex: 0, hint: "'ausrouen' vem do alemão 'ausruhen' (descansar)." },
          { type: 'translate', id: 'u8-l2-e2', promptLang: 'pt', prompt: 'Dor', acceptedAnswers: ['de Wéi', 'Wéi'], hint: "A palavra oficial em luxemburguês para 'dor' é 'Wéi' (não 'Schmerz', que é alemão), a mesma raiz de 'Kappwéi' (dor de cabeça). É masculino: 'de Wéi'." },
          { type: 'multipleChoice', id: 'u8-l2-e3', promptLang: 'lu', prompt: 'Mir ass net gutt', options: ['Não estou me sentindo bem', 'Estou muito bem', 'Estou com fome', 'Estou atrasado'], correctIndex: 0, hint: "Literalmente 'não está bom para mim' — forma comum de dizer que não se sente bem." },
          { type: 'translate', id: 'u8-l2-e4', promptLang: 'lu', prompt: 'Ech muss zum Dokter goen', acceptedAnswers: ['Eu preciso ir ao médico'], hint: "'muss...goen' = 'preciso ir', reaproveitando 'Dokter' já visto." },
          { type: 'multipleChoice', id: 'u8-l2-e5', promptLang: 'pt', prompt: 'Dor de cabeça', options: ['Kappwéi', "d'Féiwer", 'de Wéi', "d'Gesondheet"], correctIndex: 0, hint: "'Kapp' (cabeça) + 'wéi' (dor)." },
          { type: 'match', id: 'u8-l2-e6', pairs: [
            { pt: 'Descansar', lu: 'sech ausrouen', hint: "Vem do alemão 'ausruhen'." },
            { pt: 'Dor', lu: 'de Wéi', hint: "Palavra luxemburguesa para dor (não 'Schmerz'), masculino." },
            { pt: 'Febre', lu: "d'Féiwer", hint: "Grafia oficial de 'febre' (não 'Fieber')." },
            { pt: 'Farmácia', lu: "d'Apdikt", hint: "Vem do alemão 'Apotheke', feminino." },
          ] },
          { type: 'multipleChoice', id: 'u8-l2-e7', promptLang: 'lu', prompt: "d'Gesondheet", options: ['A saúde', 'A doença', 'O remédio', 'O hospital'], correctIndex: 0, hint: "'Gesondheet' vem de 'gesond' (saudável) + sufixo '-heet', equivalente a '-dade' em português." },
          { type: 'translate', id: 'u8-l2-e8', promptLang: 'pt', prompt: 'Remédio', acceptedAnswers: ["d'Medikament", 'Medikament'], hint: "'Medikament' é parecido com 'medicamento', de origem latina, e é neutro: 'd'Medikament'." },
        ],
      },
    ],
  },
  {
    id: 'u14',
    title: 'Casa e Moradia',
    description: 'Vocabulário sobre casa, cômodos e alugar um imóvel',
    level: 'B1-INICIANTE',
    lessons: [
      {
        id: 'u14-l1',
        title: 'Em casa',
        exercises: [
          { type: 'multipleChoice', id: 'u14-l1-e1', promptLang: 'lu', prompt: "d'Haus", options: ['Casa', 'Escola', 'Loja', 'Hospital'], correctIndex: 0, hint: "'Haus' vem do alemão 'Haus' (casa) e é neutro: 'd'Haus'." },
          { type: 'multipleChoice', id: 'u14-l1-e2', promptLang: 'lu', prompt: "d'Wunneng", options: ['Casa grande', 'Apartamento', 'Jardim', 'Garagem'], correctIndex: 1, hint: "'Wunneng' vem do alemão 'Wohnung' (apartamento) e é feminino: 'd'Wunneng'." },
          { type: 'translate', id: 'u14-l1-e3', promptLang: 'pt', prompt: 'Quarto', acceptedAnswers: ["d'Zëmmer", 'Zëmmer'], hint: "'Zëmmer' vem do alemão 'Zimmer' (quarto/cômodo) e é neutro: 'd'Zëmmer'." },
          { type: 'translate', id: 'u14-l1-e4', promptLang: 'pt', prompt: 'Cozinha', acceptedAnswers: ["d'Kichen", 'Kichen'], hint: "'Kichen' vem do alemão 'Küche' (cozinha) e é feminino: 'd'Kichen'." },
          { type: 'fillBlank', id: 'u14-l1-e5', promptLang: 'lu', sentence: 'Ech ___ an enger klenger Wunneng', translation: 'Eu moro em um apartamento pequeno', options: ['wunnen', 'schaffen', 'kafen', 'iessen'], correctAnswer: 'wunnen', hint: "'wunnen' vem do alemão 'wohnen' (morar)." },
          { type: 'match', id: 'u14-l1-e6', pairs: [
            { pt: 'Casa', lu: "d'Haus", hint: "Vem do alemão 'Haus', neutro." },
            { pt: 'Apartamento', lu: "d'Wunneng", hint: "Vem do alemão 'Wohnung', feminino." },
            { pt: 'Quarto', lu: "d'Zëmmer", hint: "Vem do alemão 'Zimmer', neutro." },
            { pt: 'Cozinha', lu: "d'Kichen", hint: "Vem do alemão 'Küche', feminino." },
          ] },
          { type: 'multipleChoice', id: 'u14-l1-e7', promptLang: 'pt', prompt: 'Banheiro', options: ["d'Buedzëmmer", "d'Kichen", 'de Gaart', "d'Zëmmer"], correctIndex: 0, hint: "'Buedzëmmer' vem de 'Bad' (banho) + 'Zëmmer' (cômodo), neutro." },
          { type: 'translate', id: 'u14-l1-e8', promptLang: 'lu', prompt: 'de Gaart', acceptedAnswers: ['Jardim'], hint: "'Gaart' vem do alemão 'Garten' (jardim) e é masculino: 'de Gaart'." },
        ],
      },
      {
        id: 'u14-l2',
        title: 'Alugar um imóvel',
        exercises: [
          { type: 'multipleChoice', id: 'u14-l2-e1', promptLang: 'lu', prompt: 'de Loyer', options: ['Aluguel', 'Chave', 'Vizinho', 'Andar'], correctIndex: 0, hint: "A palavra oficial para 'aluguel' é 'Loyer' (do francês), não 'Miete' (que é alemão). É masculino: 'de Loyer'." },
          { type: 'translate', id: 'u14-l2-e2', promptLang: 'pt', prompt: 'Vizinho', acceptedAnswers: ['den Noper', 'Noper'], hint: "'Noper' vem do alemão 'Nachbar' (vizinho) e é masculino: 'den Noper'." },
          { type: 'fillBlank', id: 'u14-l2-e3', promptLang: 'lu', sentence: "Den ___ vun der Wunneng ass ze héich", translation: 'O aluguel do apartamento está muito alto', options: ['Loyer', 'Kichen', 'Gaart', 'Noper'], correctAnswer: 'Loyer', hint: "'Loyer' (do francês) significa aluguel e é masculino." },
          { type: 'translate', id: 'u14-l2-e4', promptLang: 'lu', prompt: 'Ech sichen eng Wunneng', acceptedAnswers: ['Eu procuro um apartamento'], hint: "'sichen' vem do alemão 'suchen' (procurar)." },
          { type: 'multipleChoice', id: 'u14-l2-e5', promptLang: 'pt', prompt: 'Chave', options: ['de Schlëssel', 'de Loyer', 'den Noper', "d'Etage"], correctIndex: 0, hint: "'Schlëssel' vem do alemão 'Schlüssel' (chave) e é masculino: 'de Schlëssel'." },
          { type: 'match', id: 'u14-l2-e6', pairs: [
            { pt: 'Aluguel', lu: 'de Loyer', hint: "Vem do francês 'loyer', masculino." },
            { pt: 'Vizinho', lu: 'den Noper', hint: "Vem do alemão 'Nachbar', masculino." },
            { pt: 'Chave', lu: 'de Schlëssel', hint: "Vem do alemão 'Schlüssel', masculino." },
            { pt: 'Jardim', lu: 'de Gaart', hint: "Vem do alemão 'Garten', masculino." },
          ] },
          { type: 'multipleChoice', id: 'u14-l2-e7', promptLang: 'lu', prompt: "d'Etage", options: ['Andar', 'Elevador', 'Escada', 'Porta'], correctIndex: 0, hint: "'Etage' vem do francês 'étage' (andar) e é feminino: 'd'Etage'." },
          { type: 'fillBlank', id: 'u14-l2-e8', promptLang: 'lu', sentence: 'Mir wunnen am drëtten ___', translation: 'Nós moramos no terceiro andar', options: ['Etage', 'Gaart', 'Zëmmer', 'Haus'], correctAnswer: 'Etage', hint: "'Etage' significa andar." },
        ],
      },
    ],
  },
  {
    id: 'u15',
    title: 'Esportes e Lazer',
    description: 'Vocabulário de esportes, jogos e competições',
    level: 'B1-INICIANTE',
    lessons: [
      {
        id: 'u15-l1',
        title: 'Praticando esportes',
        exercises: [
          { type: 'multipleChoice', id: 'u15-l1-e1', promptLang: 'lu', prompt: 'de Sport', options: ['Esporte', 'Escola', 'Trabalho', 'Comida'], correctIndex: 0, hint: "'Sport' é escrito igual em várias línguas europeias e é masculino: 'de Sport'." },
          { type: 'multipleChoice', id: 'u15-l1-e2', promptLang: 'lu', prompt: 'de Foussball', options: ['Basquete', 'Futebol', 'Tênis', 'Natação'], correctIndex: 1, hint: "'Foussball' vem de 'Fouss' (pé) + 'Ball' (bola), como o inglês 'football'. É masculino: 'de Foussball'." },
          { type: 'translate', id: 'u15-l1-e3', promptLang: 'pt', prompt: 'Nadar', acceptedAnswers: ['schwammen'], hint: "'schwammen' vem do alemão 'schwimmen' (nadar)." },
          { type: 'translate', id: 'u15-l1-e4', promptLang: 'pt', prompt: 'Correr', acceptedAnswers: ['lafen'], hint: "'lafen' vem do alemão 'laufen' (correr)." },
          { type: 'fillBlank', id: 'u15-l1-e5', promptLang: 'lu', sentence: 'Mir ___ all Weekend Foussball', translation: 'Nós jogamos futebol todo fim de semana', options: ['spillen', 'schwammen', 'iessen', 'schlofen'], correctAnswer: 'spillen', hint: "'spillen' vem do alemão 'spielen' (jogar)." },
          { type: 'match', id: 'u15-l1-e6', pairs: [
            { pt: 'Esporte', lu: 'de Sport', hint: "Palavra internacional, masculino." },
            { pt: 'Futebol', lu: 'de Foussball', hint: "'Fouss' (pé) + 'Ball' (bola), masculino." },
            { pt: 'Nadar', lu: 'schwammen', hint: "Vem do alemão 'schwimmen'." },
            { pt: 'Correr', lu: 'lafen', hint: "Vem do alemão 'laufen'." },
          ] },
          { type: 'multipleChoice', id: 'u15-l1-e7', promptLang: 'pt', prompt: 'Time/Equipe', options: ["d'Ekipp", 'de Sport', 'de Match', 'den Training'], correctIndex: 0, hint: "'Ekipp' vem do francês 'équipe' (equipe) e é feminino: 'd'Ekipp'." },
          { type: 'translate', id: 'u15-l1-e8', promptLang: 'lu', prompt: 'gewannen', acceptedAnswers: ['Ganhar', 'Vencer', 'ganhar', 'vencer'], hint: "'gewannen' vem do alemão 'gewinnen' (ganhar)." },
        ],
      },
      {
        id: 'u15-l2',
        title: 'Competições',
        exercises: [
          { type: 'multipleChoice', id: 'u15-l2-e1', promptLang: 'lu', prompt: 'verléieren', options: ['Perder', 'Ganhar', 'Jogar', 'Treinar'], correctIndex: 0, hint: "'verléieren' vem do alemão 'verlieren' (perder)." },
          { type: 'translate', id: 'u15-l2-e2', promptLang: 'pt', prompt: 'Partida', acceptedAnswers: ['de Match', 'Match'], hint: "'Match' é emprestado do inglês, usado para 'partida', e é masculino: 'de Match'." },
          { type: 'fillBlank', id: 'u15-l2-e3', promptLang: 'lu', sentence: "Eis Ekipp huet de Match ___", translation: 'Nosso time venceu a partida', options: ['gewonnen', 'verluer', 'gespillt', 'gekacht'], correctAnswer: 'gewonnen', hint: "'gewonnen' é o particípio de 'gewannen' (ganhar). 'Match' é masculino: 'de Match'." },
          { type: 'translate', id: 'u15-l2-e4', promptLang: 'lu', prompt: 'Ech gi lafen all Moien', acceptedAnswers: ['Eu vou correr toda manhã'], hint: "Reaproveita 'lafen' (correr) já visto.", wordGlosses: { moien: 'manhã (aqui não é a saudação "Moien")' } },
          { type: 'multipleChoice', id: 'u15-l2-e5', promptLang: 'pt', prompt: 'Treino', options: ['den Training', 'de Match', "d'Ekipp", "d'Championnat"], correctIndex: 0, hint: "'Training' é quase idêntico ao inglês 'training' e é masculino: 'den Training'." },
          { type: 'match', id: 'u15-l2-e6', pairs: [
            { pt: 'Perder', lu: 'verléieren', hint: "Vem do alemão 'verlieren'." },
            { pt: 'Partida', lu: 'de Match', hint: "Emprestado do inglês, masculino." },
            { pt: 'Treino', lu: 'den Training', hint: "Quase idêntico ao inglês, masculino." },
            { pt: 'Ganhar', lu: 'gewannen', hint: "Vem do alemão 'gewinnen'." },
          ] },
          { type: 'multipleChoice', id: 'u15-l2-e7', promptLang: 'lu', prompt: "d'Championnat", options: ['O campeonato', 'O jogador', 'O estádio', 'A vitória'], correctIndex: 0, hint: "A grafia oficial é 'Championnat' (do francês), não 'Champiounschaft'." },
          { type: 'fillBlank', id: 'u15-l2-e8', promptLang: 'lu', sentence: 'Hie spillt am ___', translation: 'Ele joga no campeonato', options: ['Championnat', 'Kichen', 'Schoul', 'Apdikt'], correctAnswer: 'Championnat', hint: "'Championnat' significa campeonato (grafia oficial, do francês)." },
        ],
      },
    ],
  },
  {
    id: 'u9',
    title: 'Opiniões e Sentimentos',
    description: 'Expressar opiniões, concordar e discordar',
    level: 'B2-INICIANTE',
    lessons: [
      {
        id: 'u9-l1',
        title: 'Dar opiniões',
        exercises: [
          { type: 'multipleChoice', id: 'u9-l1-e1', promptLang: 'lu', prompt: 'mengen', options: ['Achar/pensar', 'Comer', 'Correr', 'Comprar'], correctIndex: 0, hint: "'mengen' vem do alemão 'meinen' (achar/opinar)." },
          { type: 'multipleChoice', id: 'u9-l1-e2', promptLang: 'lu', prompt: 'averstan sinn', options: ['Discordar', 'Concordar', 'Duvidar', 'Esquecer'], correctIndex: 1, hint: "Literalmente 'estar de acordo', parecido com o alemão 'einverstanden sein'." },
          { type: 'translate', id: 'u9-l1-e3', promptLang: 'pt', prompt: 'Na minha opinião', acceptedAnswers: ['Meng Meenung no'], hint: "'Meenung' vem do alemão 'Meinung' (opinião).", wordGlosses: { na: 'no (aqui: "Meenung no")', minha: 'Meng', opinião: 'Meenung' } },
          { type: 'multipleChoice', id: 'u9-l1-e4', promptLang: 'lu', prompt: 'Ech mengen datt dat richteg ass', options: ['Eu acho que isso está certo', 'Eu não sei se isso está certo', 'Eu não gosto disso', 'Eu concordo totalmente'], correctIndex: 0, hint: "'richteg' vem do alemão 'richtig' (certo/correto)." },
          { type: 'translate', id: 'u9-l1-e5', promptLang: 'lu', prompt: 'Ech si net averstan', acceptedAnswers: ['Eu não concordo', 'Eu discordo'], hint: "O prefixo 'net' nega a frase, como 'not' em inglês.", wordGlosses: { si: 'sou / estou (aqui não é o pronome "ela/eles")', averstan: 'de acordo' } },
          { type: 'match', id: 'u9-l1-e6', pairs: [
            { pt: 'Achar/pensar', lu: 'mengen', hint: "Vem do alemão 'meinen'." },
            { pt: 'Concordar', lu: 'averstan sinn', hint: "Literalmente 'estar de acordo'." },
            { pt: 'Na minha opinião', lu: 'Meng Meenung no', hint: "'Meenung' vem do alemão 'Meinung'." },
            { pt: 'Talvez', lu: 'vläicht', hint: "Vem do alemão 'vielleicht'." },
          ] },
          { type: 'multipleChoice', id: 'u9-l1-e7', promptLang: 'pt', prompt: 'Discordar', options: ['net averstan sinn', 'averstan sinn', 'mengen', 'wëssen'], correctIndex: 0, hint: "'net' nega 'averstan sinn' (concordar)." },
          { type: 'translate', id: 'u9-l1-e8', promptLang: 'lu', prompt: 'sécher', acceptedAnswers: ['Certo', 'Com certeza', 'certo', 'com certeza'], hint: "'sécher' vem do alemão 'sicher' (certo/seguro)." },
        ],
      },
      {
        id: 'u9-l2',
        title: 'Sentimentos',
        exercises: [
          { type: 'multipleChoice', id: 'u9-l2-e1', promptLang: 'lu', prompt: 'frou', options: ['Feliz', 'Triste', 'Bravo', 'Cansado'], correctIndex: 0, hint: "'frou' vem do alemão 'froh' (feliz/contente)." },
          { type: 'multipleChoice', id: 'u9-l2-e2', promptLang: 'lu', prompt: 'traureg', options: ['Feliz', 'Triste', 'Surpreso', 'Calmo'], correctIndex: 1, hint: "'traureg' vem do alemão 'traurig' (triste)." },
          { type: 'translate', id: 'u9-l2-e3', promptLang: 'pt', prompt: 'Preocupado', acceptedAnswers: ['besuergt'], hint: "'besuergt' vem do alemão 'besorgt' (preocupado)." },
          { type: 'translate', id: 'u9-l2-e4', promptLang: 'pt', prompt: 'Surpreso', acceptedAnswers: ['iwwerrascht'], hint: "'iwwerrascht' vem do alemão 'überrascht' (surpreso)." },
          { type: 'multipleChoice', id: 'u9-l2-e5', promptLang: 'lu', prompt: 'Ech si frou datt s du hei bass', options: ['Estou feliz que você esteja aqui', 'Estou triste que você saiu', 'Estou preocupado com você', 'Estou surpreso com você'], correctIndex: 0, hint: "Reaproveita 'frou' (feliz) numa frase com 'datt' (que), equivalente à conjunção em português." },
          { type: 'match', id: 'u9-l2-e6', pairs: [
            { pt: 'Feliz', lu: 'frou', hint: "Vem do alemão 'froh'." },
            { pt: 'Triste', lu: 'traureg', hint: "Vem do alemão 'traurig'." },
            { pt: 'Preocupado', lu: 'besuergt', hint: "Vem do alemão 'besorgt'." },
            { pt: 'Surpreso', lu: 'iwwerrascht', hint: "Vem do alemão 'überrascht'." },
          ] },
          { type: 'multipleChoice', id: 'u9-l2-e7', promptLang: 'pt', prompt: 'Bravo', options: ['böös', 'frou', 'midd', 'roueg'], correctIndex: 0, hint: "'böös' vem do alemão 'böse' (bravo/malvado)." },
          { type: 'translate', id: 'u9-l2-e8', promptLang: 'lu', prompt: 'roueg', acceptedAnswers: ['Calmo', 'calmo'], hint: "'roueg' vem do alemão 'ruhig' (calmo)." },
        ],
      },
    ],
  },
  {
    id: 'u16',
    title: 'Tecnologia e Internet',
    description: 'Vocabulário do mundo digital',
    level: 'B2-INICIANTE',
    lessons: [
      {
        id: 'u16-l1',
        title: 'No dia a dia digital',
        exercises: [
          { type: 'multipleChoice', id: 'u16-l1-e1', promptLang: 'lu', prompt: 'de Computer', options: ['Computador', 'Celular', 'Televisão', 'Rádio'], correctIndex: 0, hint: "'Computer' é praticamente igual em várias línguas e é masculino: 'de Computer'." },
          { type: 'multipleChoice', id: 'u16-l1-e2', promptLang: 'lu', prompt: 'de Handy', options: ['Computador', 'Celular', 'Internet', 'Senha'], correctIndex: 1, hint: "'Handy' é uma palavra alemã (apesar da aparência inglesa) para celular, e é masculino: 'de Handy'." },
          { type: 'translate', id: 'u16-l1-e3', promptLang: 'pt', prompt: 'Senha', acceptedAnswers: ["d'Passwuert", 'Passwuert'], hint: "'Passwuert' vem do inglês 'password', adaptado à grafia luxemburguesa." },
          { type: 'translate', id: 'u16-l1-e4', promptLang: 'pt', prompt: 'Internet', acceptedAnswers: ['den Internet', 'Internet'], hint: "'Internet' é uma palavra internacional e é masculino: 'den Internet'." },
          { type: 'fillBlank', id: 'u16-l1-e5', promptLang: 'lu', sentence: 'Ech muss eng E-Mail ___', translation: 'Eu preciso enviar um email', options: ['schécken', 'iessen', 'kafen', 'lafen'], correctAnswer: 'schécken', hint: "'schécken' vem do alemão 'schicken' (enviar)." },
          { type: 'match', id: 'u16-l1-e6', pairs: [
            { pt: 'Computador', lu: 'de Computer', hint: "Palavra internacional, masculino." },
            { pt: 'Celular', lu: 'de Handy', hint: "Palavra alemã, apesar da aparência inglesa, masculino." },
            { pt: 'Senha', lu: "d'Passwuert", hint: "Vem do inglês 'password'." },
            { pt: 'Internet', lu: 'den Internet', hint: "Palavra internacional, masculino." },
          ] },
          { type: 'multipleChoice', id: 'u16-l1-e7', promptLang: 'pt', prompt: 'Baixar (download)', options: ['eroflueden', 'schécken', 'kafen', 'ënnerschreiwen'], correctIndex: 0, hint: "'erof' (para baixo) + 'lueden' (carregar) = 'baixar'." },
          { type: 'translate', id: 'u16-l1-e8', promptLang: 'lu', prompt: 'online sinn', acceptedAnswers: ['Estar online', 'estar online'], hint: "'online' é um empréstimo direto do inglês." },
        ],
      },
      {
        id: 'u16-l2',
        title: 'Aparelhos e apps',
        exercises: [
          { type: 'multipleChoice', id: 'u16-l2-e1', promptLang: 'lu', prompt: 'en Apparat', options: ['Um aparelho', 'Uma senha', 'Um erro', 'Uma rede'], correctIndex: 0, hint: "'Apparat' vem do francês/alemão 'appareil/Apparat' (aparelho)." },
          { type: 'translate', id: 'u16-l2-e2', promptLang: 'pt', prompt: 'Aplicativo', acceptedAnswers: ["d'App", 'App'], hint: "'App' é a forma curta internacional de 'application' e é feminino: 'd'App'." },
          { type: 'fillBlank', id: 'u16-l2-e3', promptLang: 'lu', sentence: 'Ech hu mäi ___ vergiess doheem', translation: 'Eu esqueci meu celular em casa', options: ['Handy', 'Passwuert', 'Internet', 'Apparat'], correctAnswer: 'Handy', hint: "'Handy' significa celular." },
          { type: 'translate', id: 'u16-l2-e4', promptLang: 'lu', prompt: "D'Bibliothéik huet gratis Internet", acceptedAnswers: ['A biblioteca tem internet grátis'], hint: "Reaproveita 'Bibliothéik' (biblioteca) e 'gratis' já vistos." },
          { type: 'multipleChoice', id: 'u16-l2-e5', promptLang: 'pt', prompt: 'Rede social', options: ['sozial Netzwierk', "d'App", 'en Apparat', 'e Feeler'], correctIndex: 0, hint: "'sozial Netzwierk' vem do alemão 'soziales Netzwerk' (rede social)." },
          { type: 'match', id: 'u16-l2-e6', pairs: [
            { pt: 'Aparelho', lu: 'en Apparat', hint: "Vem do francês/alemão 'appareil/Apparat'." },
            { pt: 'Aplicativo', lu: "d'App", hint: "Forma curta de 'application', feminino." },
            { pt: 'Rede social', lu: 'sozial Netzwierk', hint: "Vem do alemão 'soziales Netzwerk'." },
            { pt: 'Senha', lu: "d'Passwuert", hint: "Vem do inglês 'password'." },
          ] },
          { type: 'multipleChoice', id: 'u16-l2-e7', promptLang: 'lu', prompt: 'e Feeler', options: ['Um erro', 'Uma senha', 'Um aparelho', 'Uma rede'], correctIndex: 0, hint: "'Feeler' vem do alemão 'Fehler' (erro)." },
          { type: 'fillBlank', id: 'u16-l2-e8', promptLang: 'lu', sentence: "D'App huet e ___", translation: 'O aplicativo tem um erro', options: ['Feeler', 'Apparat', 'Passwuert', 'Netzwierk'], correctAnswer: 'Feeler', hint: "'Feeler' significa erro." },
        ],
      },
    ],
  },
  {
    id: 'u17',
    title: 'Relacionamentos',
    description: 'Falar sobre amizade, amor e família formada',
    level: 'B2-INICIANTE',
    lessons: [
      {
        id: 'u17-l1',
        title: 'Amizade e confiança',
        exercises: [
          { type: 'multipleChoice', id: 'u17-l1-e1', promptLang: 'lu', prompt: 'de Frënd', options: ['Amigo', 'Inimigo', 'Vizinho', 'Colega'], correctIndex: 0, hint: "'Frënd' vem do alemão 'Freund' (amigo) e é masculino: 'de Frënd'." },
          { type: 'multipleChoice', id: 'u17-l1-e2', promptLang: 'lu', prompt: "d'Bezéiung", options: ['Trabalho', 'Relacionamento', 'Viagem', 'Estudo'], correctIndex: 1, hint: "'Bezéiung' vem do alemão 'Beziehung' (relacionamento) e é feminino: 'd'Bezéiung'." },
          { type: 'translate', id: 'u17-l1-e3', promptLang: 'pt', prompt: 'Confiar', acceptedAnswers: ['vertrauen'], hint: "'vertrauen' vem do alemão 'vertrauen' (confiar)." },
          { type: 'translate', id: 'u17-l1-e4', promptLang: 'pt', prompt: 'Casar', acceptedAnswers: ['bestueden'], hint: "'bestueden' está relacionado ao rito de casamento em luxemburguês." },
          { type: 'fillBlank', id: 'u17-l1-e5', promptLang: 'lu', sentence: 'Ech hu vill ___ zu menger Famill', translation: 'Eu tenho muita confiança na minha família', options: ['Vertrauen', 'Bezéiung', 'Frënd', 'Hochzäit'], correctAnswer: 'Vertrauen', hint: "'Vertrauen' significa confiança." },
          { type: 'match', id: 'u17-l1-e6', pairs: [
            { pt: 'Amigo', lu: 'de Frënd', hint: "Vem do alemão 'Freund', masculino." },
            { pt: 'Relacionamento', lu: "d'Bezéiung", hint: "Vem do alemão 'Beziehung', feminino." },
            { pt: 'Confiar', lu: 'vertrauen', hint: "Vem do alemão 'vertrauen'." },
            { pt: 'Casar', lu: 'bestueden', hint: "Relacionado ao rito de casamento." },
          ] },
          { type: 'multipleChoice', id: 'u17-l1-e7', promptLang: 'pt', prompt: 'Casamento', options: ["d'Hochzäit", "d'Bezéiung", "d'Scheedung", 'de Frënd'], correctIndex: 0, hint: "'Hochzäit' vem do alemão 'Hochzeit' (casamento) e é feminino: 'd'Hochzäit'." },
          { type: 'translate', id: 'u17-l1-e8', promptLang: 'lu', prompt: 'sech trennen', acceptedAnswers: ['Se separar', 'se separar'], hint: "'trennen' vem do alemão 'trennen' (separar)." },
        ],
      },
      {
        id: 'u17-l2',
        title: 'Amor e família',
        exercises: [
          { type: 'multipleChoice', id: 'u17-l2-e1', promptLang: 'lu', prompt: 'sech gär hunn', options: ['Gostar um do outro', 'Se separar', 'Discutir', 'Esquecer'], correctIndex: 0, hint: "Literalmente 'ter-se com carinho' — expressão para dizer que duas pessoas se gostam." },
          { type: 'translate', id: 'u17-l2-e2', promptLang: 'pt', prompt: 'Namorado(a)', acceptedAnswers: ['Frëndin', 'de Frënd', "d'Frëndin", 'Frënd'], hint: "A palavra oficial em luxemburguês é o próprio 'Frënd' (namorado) / 'Frëndin' (namorada) — 'Copain/Copine' não são palavras do dicionário oficial." },
          { type: 'fillBlank', id: 'u17-l2-e3', promptLang: 'lu', sentence: 'Si ___ sech scho zéng Joer', translation: 'Eles se gostam há dez anos', options: ['hunn sech gär', 'trennen sech', 'bestueden', 'vertrauen'], correctAnswer: 'hunn sech gär', hint: "'sech gär hunn' significa gostar um do outro." },
          { type: 'translate', id: 'u17-l2-e4', promptLang: 'lu', prompt: 'Mir sinn zesummen', acceptedAnswers: ['Nós estamos juntos'], hint: "'zesummen' vem do alemão 'zusammen' (juntos)." },
          { type: 'multipleChoice', id: 'u17-l2-e5', promptLang: 'pt', prompt: 'Divórcio', options: ["d'Scheedung", "d'Hochzäit", "d'Bezéiung", "d'Frëndin"], correctIndex: 0, hint: "'Scheedung' vem do alemão 'Scheidung' (divórcio) e é feminino: 'd'Scheedung'." },
          { type: 'match', id: 'u17-l2-e6', pairs: [
            { pt: 'Namorada', lu: "d'Frëndin", hint: "Forma feminina de 'Frënd' — não existe 'Copine' no dicionário oficial." },
            { pt: 'Juntos', lu: 'zesummen', hint: "Vem do alemão 'zusammen'." },
            { pt: 'Divórcio', lu: "d'Scheedung", hint: "Vem do alemão 'Scheidung', feminino." },
            { pt: 'Casamento', lu: "d'Hochzäit", hint: "Vem do alemão 'Hochzeit', feminino." },
          ] },
          { type: 'multipleChoice', id: 'u17-l2-e7', promptLang: 'lu', prompt: "d'Famill grënnen", options: ['Formar uma família', 'Comprar uma casa', 'Fazer uma viagem', 'Mudar de emprego'], correctIndex: 0, hint: "'grënnen' vem do alemão 'gründen' (fundar/formar)." },
          { type: 'fillBlank', id: 'u17-l2-e8', promptLang: 'lu', sentence: 'Si wëllen eng ___ grënnen', translation: 'Eles querem formar uma família', options: ['Famill', 'Bezéiung', 'Scheedung', 'Hochzäit'], correctAnswer: 'Famill', hint: "'Famill' significa família, já visto antes." },
        ],
      },
    ],
  },
  {
    id: 'u22',
    title: 'Meio Ambiente',
    description: 'Vocabulário sobre natureza e sustentabilidade',
    level: 'B2-INICIANTE',
    lessons: [
      {
        id: 'u22-l1',
        title: 'Cuidando do planeta',
        exercises: [
          { type: 'multipleChoice', id: 'u22-l1-e1', promptLang: 'lu', prompt: 'recycléieren', options: ['Reciclar', 'Jogar fora', 'Comprar', 'Vender'], correctIndex: 0, hint: "'recycléieren' vem do francês/inglês 'recycler/recycle'." },
          { type: 'multipleChoice', id: 'u22-l1-e2', promptLang: 'lu', prompt: "d'Offall", options: ['O lixo', 'A água', 'O ar', 'A terra'], correctIndex: 0, hint: "'Offall' vem do alemão 'Abfall' (lixo)." },
          { type: 'translate', id: 'u22-l1-e3', promptLang: 'pt', prompt: 'Economizar', acceptedAnswers: ['spueren'], hint: "'spueren' vem do alemão 'sparen' (economizar/poupar)." },
          { type: 'translate', id: 'u22-l1-e4', promptLang: 'pt', prompt: 'Natureza', acceptedAnswers: ["d'Natur", 'Natur'], hint: "'Natur' é praticamente igual em várias línguas europeias." },
          { type: 'fillBlank', id: 'u22-l1-e5', promptLang: 'lu', sentence: "Mir mussen d'Natur ___", translation: 'Nós precisamos proteger a natureza', options: ['schützen', 'spueren', 'kafen', 'verkeeafen'], correctAnswer: 'schützen', hint: "'schützen' vem do alemão 'schützen' (proteger)." },
          { type: 'match', id: 'u22-l1-e6', pairs: [
            { pt: 'Reciclar', lu: 'recycléieren', hint: "Vem do francês/inglês 'recycle'." },
            { pt: 'Lixo', lu: "d'Offall", hint: "Vem do alemão 'Abfall'." },
            { pt: 'Economizar', lu: 'spueren', hint: "Vem do alemão 'sparen'." },
            { pt: 'Natureza', lu: "d'Natur", hint: "Palavra internacional." },
          ] },
          { type: 'multipleChoice', id: 'u22-l1-e7', promptLang: 'pt', prompt: 'Ar', options: ["d'Loft", "d'Offall", "d'Natur", "d'Energie"], correctIndex: 0, hint: "'Loft' vem do alemão 'Luft' (ar)." },
          { type: 'translate', id: 'u22-l1-e8', promptLang: 'lu', prompt: 'rengen', acceptedAnswers: ['Limpar', 'limpar'], hint: "'rengen' vem do alemão 'reinigen' (limpar)." },
        ],
      },
      {
        id: 'u22-l2',
        title: 'Energia sustentável',
        exercises: [
          { type: 'multipleChoice', id: 'u22-l2-e1', promptLang: 'lu', prompt: "d'Energie", options: ['A energia', 'O lixo', 'O ar', 'A água'], correctIndex: 0, hint: "'Energie' é praticamente igual em várias línguas." },
          { type: 'multipleChoice', id: 'u22-l2-e2', promptLang: 'lu', prompt: 'erneierbar', options: ['Renovável', 'Poluído', 'Caro', 'Perigoso'], correctIndex: 0, hint: "'erneierbar' vem do alemão 'erneuerbar' (renovável)." },
          { type: 'translate', id: 'u22-l2-e3', promptLang: 'pt', prompt: 'Proteger', acceptedAnswers: ['schützen'], hint: "'schützen' vem do alemão 'schützen'." },
          { type: 'translate', id: 'u22-l2-e4', promptLang: 'pt', prompt: 'Poluição', acceptedAnswers: ["d'Pollutioun", 'Pollutioun'], hint: "'Pollutioun' vem do francês 'pollution'." },
          { type: 'fillBlank', id: 'u22-l2-e5', promptLang: 'lu', sentence: 'Mir sollten méi erneierbar ___ benotzen', translation: 'Nós deveríamos usar mais energia renovável', options: ['Energie', 'Offall', 'Natur', 'Loft'], correctAnswer: 'Energie', hint: "'Energie' significa energia." },
          { type: 'match', id: 'u22-l2-e6', pairs: [
            { pt: 'Energia', lu: "d'Energie", hint: "Palavra internacional." },
            { pt: 'Renovável', lu: 'erneierbar', hint: "Vem do alemão 'erneuerbar'." },
            { pt: 'Poluição', lu: "d'Pollutioun", hint: "Vem do francês 'pollution'." },
            { pt: 'Proteger', lu: 'schützen', hint: "Vem do alemão 'schützen'." },
          ] },
          { type: 'multipleChoice', id: 'u22-l2-e7', promptLang: 'lu', prompt: "d'Zukunft", options: ['O futuro', 'O passado', 'O presente', 'A história'], correctIndex: 0, hint: "'Zukunft' vem do alemão 'Zukunft' (futuro), já visto antes." },
          { type: 'translate', id: 'u22-l2-e8', promptLang: 'pt', prompt: 'Sustentável', acceptedAnswers: ['nohalteg'], hint: "'nohalteg' vem do alemão 'nachhaltig' (sustentável)." },
        ],
      },
    ],
  },
];
