import { Unit } from '../types/content';

/**
 * The new A1 "objective" units: Ícone -> 5 barras -> 10 exercises each.
 * Only the first 4 of the planned 20 objectives are authored so far (the
 * rest will follow in later passes, same depth/format). Every word here
 * was cross-checked against the official Lëtzebuerger Online Dictionnaire
 * (LOD) this session before use.
 */
export const a1Objectives: Unit[] = [
  {
    id: 'a1-obj1',
    title: 'Saudações',
    description: 'Cumprimentar, se despedir e ser gentil em luxemburguês',
    level: 'A1-INICIANTE',
    kind: 'objective',
    icon: '👋',
    lessons: [
      {
        id: 'a1-obj1-b1',
        title: 'Barra 1 · Introdução',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj1-b1-e1', promptLang: 'lu', prompt: 'Moien', options: ['Olá', 'Tchau', 'Obrigado', 'Sim'], correctIndex: 0, hint: "'Moien' vem do alemão 'Morgen' (manhã) e virou uma saudação usada a qualquer hora do dia." },
          { type: 'multipleChoice', id: 'a1-obj1-b1-e2', promptLang: 'lu', prompt: 'Äddi', options: ['Tchau', 'Olá', 'Bom dia', 'Não'], correctIndex: 0, hint: "'Äddi' vem do francês 'adieu'." },
          { type: 'multipleChoice', id: 'a1-obj1-b1-e3', promptLang: 'lu', prompt: 'Merci', options: ['Obrigado', 'Tchau', 'Olá', 'Sim'], correctIndex: 0, hint: "'Merci' é emprestado diretamente do francês." },
          { type: 'multipleChoice', id: 'a1-obj1-b1-e4', promptLang: 'pt', prompt: 'Sim', options: ['Jo', 'Neen', 'Merci', 'Äddi'], correctIndex: 0, hint: "'Jo' é parecido com o alemão 'ja'." },
          { type: 'multipleChoice', id: 'a1-obj1-b1-e5', promptLang: 'lu', prompt: 'Neen', options: ['Não', 'Sim', 'Tchau', 'Olá'], correctIndex: 0, hint: "'Neen' é parecido com o alemão 'nein'." },
          { type: 'multipleChoice', id: 'a1-obj1-b1-e6', promptLang: 'lu', prompt: 'Wann ech gelift', options: ['Por favor', 'Desculpe', 'Obrigado', 'Sim'], correctIndex: 0, hint: "Literalmente 'se eu quisesse' — a forma padrão de dizer 'por favor'." },
          { type: 'multipleChoice', id: 'a1-obj1-b1-e7', promptLang: 'lu', prompt: 'Entschëllegt', options: ['Desculpe', 'Por favor', 'Obrigado', 'Sim'], correctIndex: 0, hint: "Vem do alemão 'entschuldigen'." },
          { type: 'match', id: 'a1-obj1-b1-e8', pairs: [
            { pt: 'Olá', lu: 'Moien', hint: "Saudação geral, a qualquer hora." },
            { pt: 'Tchau', lu: 'Äddi', hint: "Vem do francês 'adieu'." },
            { pt: 'Obrigado', lu: 'Merci', hint: "Empréstimo direto do francês." },
            { pt: 'Sim', lu: 'Jo', hint: "Parecido com o alemão 'ja'." },
          ] },
          { type: 'match', id: 'a1-obj1-b1-e9', pairs: [
            { pt: 'Não', lu: 'Neen', hint: "Parecido com o alemão 'nein'." },
            { pt: 'Por favor', lu: 'Wann ech gelift', hint: "Literalmente 'se eu quisesse'." },
            { pt: 'Desculpe', lu: 'Entschëllegt', hint: "Vem do alemão 'entschuldigen'." },
            { pt: 'Até logo', lu: 'Bis Bald', hint: "Quase idêntico ao alemão 'bis bald'." },
          ] },
          { type: 'fillBlank', id: 'a1-obj1-b1-e10', promptLang: 'lu', sentence: 'Merci, ___', translation: 'Obrigado, tchau', options: ['Äddi', 'Moien', 'Jo', 'Neen'], correctAnswer: 'Äddi', hint: "'Äddi' se despede depois do 'Merci'." },
        ],
      },
      {
        id: 'a1-obj1-b2',
        title: 'Barra 2 · Como vai',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj1-b2-e1', promptLang: 'lu', prompt: 'Bis Bald', options: ['Até logo', 'Tchau', 'Olá', 'Obrigado'], correctIndex: 0, hint: "Quase idêntico ao alemão 'bis bald'." },
          { type: 'multipleChoice', id: 'a1-obj1-b2-e2', promptLang: 'lu', prompt: 'geet', options: ['vai', 'vem', 'dorme', 'fala'], correctIndex: 0, hint: "Vem do verbo 'goen' (ir) — aqui usado como em 'como vai'." },
          { type: 'multipleChoice', id: 'a1-obj1-b2-e3', promptLang: 'lu', prompt: 'gutt', options: ['bem / bom', 'ruim', 'grande', 'triste'], correctIndex: 0, hint: "Vem do alemão 'gut'." },
          { type: 'multipleChoice', id: 'a1-obj1-b2-e4', promptLang: 'lu', prompt: 'et', options: ['isso (impessoal)', 'eu', 'você', 'nós'], correctIndex: 0, hint: "Pronome impessoal, como o 'it' de 'it's raining' em inglês — não se traduz sozinho." },
          { type: 'multipleChoice', id: 'a1-obj1-b2-e5', promptLang: 'lu', prompt: 'mir', options: ['para mim', 'nós', 'você', 'eles'], correctIndex: 0, hint: "Aqui é o dativo de 'ech' ('para mim'). O mesmo 'mir' também significa 'nós' em outros contextos — o sentido depende da frase." },
          { type: 'match', id: 'a1-obj1-b2-e6', pairs: [
            { pt: 'vai', lu: 'geet' },
            { pt: 'bem / bom', lu: 'gutt' },
            { pt: 'isso (impessoal)', lu: 'et' },
            { pt: 'para mim', lu: 'mir' },
          ] },
          { type: 'fillBlank', id: 'a1-obj1-b2-e7', promptLang: 'lu', sentence: 'Et geet mir ___', translation: 'Estou bem', options: ['gutt', 'Moien', 'Äddi', 'Merci'], correctAnswer: 'gutt', hint: "Literalmente 'isso vai bem para mim' — todas as palavras já foram vistas." },
          { type: 'match', id: 'a1-obj1-b2-e8', pairs: [
            { pt: 'Estou bem', lu: 'Et geet mir gutt' },
            { pt: 'Até logo', lu: 'Bis Bald' },
            { pt: 'Olá', lu: 'Moien' },
            { pt: 'Obrigado', lu: 'Merci' },
          ] },
          { type: 'translate', id: 'a1-obj1-b2-e9', promptLang: 'lu', prompt: 'Et geet mir gutt', acceptedAnswers: ['Estou bem', 'estou bem'], hint: "Literalmente 'vai bem para mim' — reaproveita 'et', 'geet', 'mir' e 'gutt', já vistos individualmente." },
          { type: 'multipleChoice', id: 'a1-obj1-b2-e10', promptLang: 'lu', prompt: 'Gudde Mëtteg', options: ['Boa tarde', 'Bom dia', 'Boa noite', 'Até logo'], correctIndex: 0, hint: "'Mëtteg' vem do alemão 'Mittag' (meio-dia/tarde)." },
        ],
      },
      {
        id: 'a1-obj1-b3',
        title: 'Barra 3 · Qual é seu nome',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj1-b3-e1', promptLang: 'lu', prompt: 'wéi', options: ['como / qual', 'quando', 'onde', 'quem'], correctIndex: 0, hint: "Palavra de pergunta — 'como' ou 'qual', dependendo do contexto." },
          { type: 'multipleChoice', id: 'a1-obj1-b3-e2', promptLang: 'lu', prompt: 'du', options: ['você / tu', 'eu', 'nós', 'eles'], correctIndex: 0 },
          { type: 'multipleChoice', id: 'a1-obj1-b3-e3', promptLang: 'lu', prompt: 'heeschs', options: ['chama(-se)', 'vai', 'mora', 'gosta'], correctIndex: 0, hint: "Vem de 'heeschen' (chamar-se)." },
          { type: 'match', id: 'a1-obj1-b3-e4', pairs: [
            { pt: 'como / qual', lu: 'wéi' },
            { pt: 'você / tu', lu: 'du' },
            { pt: 'chama(-se)', lu: 'heeschs' },
            { pt: 'bem / bom', lu: 'gutt' },
          ] },
          { type: 'multipleChoice', id: 'a1-obj1-b3-e5', promptLang: 'lu', prompt: 'Wéi geet et?', options: ['Como vai?', 'Qual é seu nome?', 'Onde mora?', 'Até logo'], correctIndex: 0, hint: "Literalmente 'como vai isso?' — todas as palavras já foram vistas." },
          { type: 'fillBlank', id: 'a1-obj1-b3-e6', promptLang: 'lu', sentence: '___ geet et?', translation: 'Como vai?', options: ['Wéi', 'Moien', 'Äddi', 'Jo'], correctAnswer: 'Wéi' },
          { type: 'multipleChoice', id: 'a1-obj1-b3-e7', promptLang: 'lu', prompt: 'Wéi heeschs du?', options: ['Qual é o seu nome?', 'Como vai?', 'Até logo', 'Boa noite'], correctIndex: 0 },
          { type: 'match', id: 'a1-obj1-b3-e8', pairs: [
            { pt: 'Como vai?', lu: 'Wéi geet et?' },
            { pt: 'Qual é o seu nome?', lu: 'Wéi heeschs du?' },
            { pt: 'Estou bem', lu: 'Et geet mir gutt' },
            { pt: 'Olá', lu: 'Moien' },
          ] },
          { type: 'translate', id: 'a1-obj1-b3-e9', promptLang: 'lu', prompt: 'Wéi geet et?', acceptedAnswers: ['Como vai?', 'como vai?'] },
          { type: 'translate', id: 'a1-obj1-b3-e10', promptLang: 'lu', prompt: 'Wéi heeschs du?', acceptedAnswers: ['Qual é o seu nome?', 'Qual é seu nome?'] },
        ],
      },
      {
        id: 'a1-obj1-b4',
        title: 'Barra 4 · Aplicação',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj1-b4-e1', promptLang: 'lu', prompt: 'Gutt Nuecht', options: ['Boa noite (despedida)', 'Bom dia', 'Boa tarde', 'Até logo'], correctIndex: 0, hint: "'Nuecht' vem do alemão 'Nacht' (noite) — 'gutt' você já conhece." },
          { type: 'multipleChoice', id: 'a1-obj1-b4-e2', promptLang: 'lu', prompt: 'Merci fir Ären Hëllef', options: ['Obrigado pela sua ajuda', 'Por favor', 'Desculpe', 'Até logo'], correctIndex: 0, hint: "'Hëllef' significa ajuda — 'Merci' você já conhece." },
          { type: 'multipleChoice', id: 'a1-obj1-b4-e3', promptLang: 'lu', prompt: 'Gär geschitt', options: ['De nada', 'Por favor', 'Obrigado', 'Desculpe'], correctIndex: 0, hint: "Resposta padrão a um 'merci' — 'de nada'." },
          { type: 'match', id: 'a1-obj1-b4-e4', pairs: [
            { pt: 'Boa noite (despedida)', lu: 'Gutt Nuecht' },
            { pt: 'Obrigado pela sua ajuda', lu: 'Merci fir Ären Hëllef' },
            { pt: 'De nada', lu: 'Gär geschitt' },
            { pt: 'Boa tarde', lu: 'Gudde Mëtteg' },
          ] },
          { type: 'fillBlank', id: 'a1-obj1-b4-e5', promptLang: 'lu', sentence: 'Merci fir Ären ___', translation: 'Obrigado pela sua ajuda', options: ['Hëllef', 'Numm', 'Alter', 'Land'], correctAnswer: 'Hëllef' },
          { type: 'multipleChoice', id: 'a1-obj1-b4-e6', promptLang: 'pt', prompt: 'Você quer se despedir à noite, antes de dormir. O que você diz?', options: ['Gutt Nuecht', 'Gudde Mëtteg', 'Moien', 'Wéi geet et?'], correctIndex: 0 },
          { type: 'multipleChoice', id: 'a1-obj1-b4-e7', promptLang: 'pt', prompt: 'Você esbarrou em alguém sem querer. O que você diz?', options: ['Entschëllegt', 'Merci', 'Moien', 'Bis Bald'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj1-b4-e8', promptLang: 'lu', prompt: 'Merci fir Ären Hëllef', acceptedAnswers: ['Obrigado pela sua ajuda'] },
          { type: 'translate', id: 'a1-obj1-b4-e9', promptLang: 'lu', prompt: 'Gär geschitt', acceptedAnswers: ['De nada', 'de nada'] },
          { type: 'multipleChoice', id: 'a1-obj1-b4-e10', promptLang: 'lu', prompt: 'Entschëllegt, wéi heeschs du?', options: ['Desculpe, qual é o seu nome?', 'Obrigado, até logo', 'Como vai, boa tarde?', 'De nada, tchau'], correctIndex: 0, hint: "'Entschëllegt' e 'Wéi heeschs du?' você já conhece separadamente — aqui só combinados." },
        ],
      },
      {
        id: 'a1-obj1-b5',
        title: 'Barra 5 · Desafio',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj1-b5-e1', promptLang: 'lu', prompt: 'Moien', options: ['Olá', 'Tchau', 'Obrigado', 'Sim'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj1-b5-e2', promptLang: 'pt', prompt: 'Tchau', acceptedAnswers: ['Äddi'] },
          { type: 'fillBlank', id: 'a1-obj1-b5-e3', promptLang: 'lu', sentence: '___ geet et?', translation: 'Como vai?', options: ['Wéi', 'Moien', 'Merci', 'Jo'], correctAnswer: 'Wéi' },
          { type: 'orderWords', id: 'a1-obj1-b5-e4', translation: 'Boa noite, até logo', words: ['Gutt', 'Nuecht,', 'bis', 'Bald'], correctOrder: ['Gutt', 'Nuecht,', 'bis', 'Bald'] },
          { type: 'translate', id: 'a1-obj1-b5-e5', promptLang: 'lu', prompt: 'Gär geschitt', acceptedAnswers: ['De nada'] },
          { type: 'multipleChoice', id: 'a1-obj1-b5-e6', promptLang: 'pt', prompt: 'Qual é a forma correta de pedir desculpas?', options: ['Entschëllegt', 'Merci', 'Wann ech gelift', 'Bis Bald'], correctIndex: 0 },
          { type: 'fillBlank', id: 'a1-obj1-b5-e7', promptLang: 'lu', sentence: 'Merci fir Ären ___', translation: 'Obrigado pela sua ajuda', options: ['Hëllef', 'Numm', 'Land', 'Alter'], correctAnswer: 'Hëllef' },
          { type: 'match', id: 'a1-obj1-b5-e8', pairs: [
            { pt: 'Bom dia/boa tarde', lu: 'Gudde Mëtteg' },
            { pt: 'Boa noite (despedida)', lu: 'Gutt Nuecht' },
            { pt: 'De nada', lu: 'Gär geschitt' },
            { pt: 'Como vai?', lu: 'Wéi geet et?' },
          ] },
          { type: 'multipleChoice', id: 'a1-obj1-b5-e9', promptLang: 'lu', prompt: 'Moien, wéi heeschs du?', options: ['Olá, qual é o seu nome?', 'Obrigado, até logo', 'Boa tarde, como vai?', 'De nada, tchau'], correctIndex: 0, hint: "'Moien' e 'Wéi heeschs du?' você já conhece separadamente — aqui só combinados." },
          { type: 'translate', id: 'a1-obj1-b5-e10', promptLang: 'lu', prompt: 'Moien, wéi heeschs du?', acceptedAnswers: ['Olá, qual é o seu nome?', 'Olá, qual é seu nome?'] },
        ],
      },
    ],
  },
  {
    id: 'a1-obj2',
    title: 'Eu e Você',
    description: 'Falar seu nome, idade, origem e onde você mora',
    level: 'A1-INICIANTE',
    kind: 'objective',
    icon: '🙋',
    lessons: [
      {
        id: 'a1-obj2-b1',
        title: 'Barra 1 · Introdução',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj2-b1-e1', promptLang: 'lu', prompt: 'den Numm', options: ['O nome', 'A idade', 'O país', 'A casa'], correctIndex: 0, hint: "'Numm' é masculino: 'den Numm'." },
          { type: 'translate', id: 'a1-obj2-b1-e2', promptLang: 'pt', prompt: 'Idade', acceptedAnswers: ['den Alter', 'Alter'], hint: "'Alter' é masculino: 'den Alter'." },
          { type: 'multipleChoice', id: 'a1-obj2-b1-e3', promptLang: 'lu', prompt: 'de Joer', options: ['O ano', 'O mês', 'O dia', 'A hora'], correctIndex: 0, hint: "'Joer' também é usado no plural pra falar de idade (X Joer al)." },
          { type: 'translate', id: 'a1-obj2-b1-e4', promptLang: 'pt', prompt: 'País', acceptedAnswers: ["d'Land", 'Land'], hint: "'Land' é neutro: 'd'Land'." },
          { type: 'multipleChoice', id: 'a1-obj2-b1-e5', promptLang: 'lu', prompt: 'wunnen', options: ['Morar', 'Comer', 'Trabalhar', 'Estudar'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj2-b1-e6', promptLang: 'pt', prompt: 'Vir', acceptedAnswers: ['kommen'] },
          { type: 'multipleChoice', id: 'a1-obj2-b1-e7', promptLang: 'lu', prompt: 'Lëtzebuerg', options: ['Luxemburgo', 'Portugal', 'Brasil', 'França'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj2-b1-e8', promptLang: 'pt', prompt: 'Portugal', acceptedAnswers: ['Portugal'] },
          { type: 'match', id: 'a1-obj2-b1-e9', pairs: [
            { pt: 'Nome', lu: 'den Numm' },
            { pt: 'Idade', lu: 'den Alter' },
            { pt: 'País', lu: "d'Land" },
            { pt: 'Morar', lu: 'wunnen' },
          ] },
          { type: 'translate', id: 'a1-obj2-b1-e10', promptLang: 'lu', prompt: 'Brasilien', acceptedAnswers: ['Brasil'] },
        ],
      },
      {
        id: 'a1-obj2-b2',
        title: 'Barra 2 · Compreensão',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj2-b2-e1', promptLang: 'lu', prompt: 'Wéi al bass du?', options: ['Quantos anos você tem?', 'Qual é seu nome?', 'Onde você mora?', 'De onde você vem?'], correctIndex: 0, hint: "Literalmente 'como velho és tu?'." },
          { type: 'translate', id: 'a1-obj2-b2-e2', promptLang: 'lu', prompt: 'Ech sinn zwanzeg Joer al', acceptedAnswers: ['Eu tenho vinte anos'] },
          { type: 'fillBlank', id: 'a1-obj2-b2-e3', promptLang: 'lu', sentence: 'Ech sinn zwanzeg Joer ___', translation: 'Eu tenho vinte anos', options: ['al', 'gutt', 'frou', 'midd'], correctAnswer: 'al' },
          { type: 'multipleChoice', id: 'a1-obj2-b2-e4', promptLang: 'pt', prompt: 'Onde você mora?', options: ['Wou wunns du?', 'Wéi al bass du?', 'Wéi heeschs du?', 'Vu wou kënns du?'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj2-b2-e5', promptLang: 'lu', prompt: 'Ech wunnen zu Lëtzebuerg', acceptedAnswers: ['Eu moro em Luxemburgo'] },
          { type: 'match', id: 'a1-obj2-b2-e6', pairs: [
            { pt: 'Quantos anos você tem?', lu: 'Wéi al bass du?' },
            { pt: 'Onde você mora?', lu: 'Wou wunns du?' },
            { pt: 'De onde você vem?', lu: 'Vu wou kënns du?' },
            { pt: 'Eu moro em Luxemburgo', lu: 'Ech wunnen zu Lëtzebuerg' },
          ] },
          { type: 'multipleChoice', id: 'a1-obj2-b2-e7', promptLang: 'lu', prompt: 'Vu wou kënns du?', options: ['De onde você vem?', 'Onde você mora?', 'Quantos anos você tem?', 'Qual é seu nome?'], correctIndex: 0 },
          { type: 'fillBlank', id: 'a1-obj2-b2-e8', promptLang: 'lu', sentence: 'Ech ___ aus Portugal', translation: 'Eu venho de Portugal', options: ['kommen', 'wunnen', 'heeschen', 'sinn'], correctAnswer: 'kommen' },
          { type: 'translate', id: 'a1-obj2-b2-e9', promptLang: 'pt', prompt: 'Eu venho do Brasil', acceptedAnswers: ['Ech kommen aus Brasilien'] },
          { type: 'multipleChoice', id: 'a1-obj2-b2-e10', promptLang: 'lu', prompt: 'Ech wunnen zu Lëtzebuerg', options: ['Eu moro em Luxemburgo', 'Eu venho de Luxemburgo', 'Eu sou de Luxemburgo', 'Eu trabalho em Luxemburgo'], correctIndex: 0 },
        ],
      },
      {
        id: 'a1-obj2-b3',
        title: 'Barra 3 · Construção',
        exercises: [
          { type: 'orderWords', id: 'a1-obj2-b3-e1', translation: 'Eu moro em Luxemburgo', words: ['Ech', 'wunnen', 'zu', 'Lëtzebuerg'], correctOrder: ['Ech', 'wunnen', 'zu', 'Lëtzebuerg'], itemIds: ['word:wunnen'] },
          { type: 'fillBlank', id: 'a1-obj2-b3-e2', promptLang: 'lu', sentence: 'Ech kommen ___ Portugal', translation: 'Eu venho de Portugal', options: ['aus', 'zu', 'an', 'vu'], correctAnswer: 'aus' },
          { type: 'orderWords', id: 'a1-obj2-b3-e3', translation: 'Eu tenho vinte anos', words: ['Ech', 'sinn', 'zwanzeg', 'Joer', 'al'], correctOrder: ['Ech', 'sinn', 'zwanzeg', 'Joer', 'al'] },
          { type: 'translate', id: 'a1-obj2-b3-e4', promptLang: 'pt', prompt: 'Quantos anos você tem?', acceptedAnswers: ['Wéi al bass du?'] },
          { type: 'fillBlank', id: 'a1-obj2-b3-e5', promptLang: 'lu', sentence: '___ al bass du?', translation: 'Quantos anos você tem?', options: ['Wéi', 'Wou', 'Wat', 'Wann'], correctAnswer: 'Wéi' },
          { type: 'orderWords', id: 'a1-obj2-b3-e6', translation: 'De onde você vem?', words: ['Vu', 'wou', 'kënns', 'du?'], correctOrder: ['Vu', 'wou', 'kënns', 'du?'] },
          { type: 'translate', id: 'a1-obj2-b3-e7', promptLang: 'lu', prompt: 'Ech heeschen Ana a sinn zwanzeg Joer al', acceptedAnswers: ['Eu me chamo Ana e tenho vinte anos'] },
          { type: 'fillBlank', id: 'a1-obj2-b3-e8', promptLang: 'lu', sentence: 'Ech ___ zu Lëtzebuerg', translation: 'Eu moro em Luxemburgo', options: ['wunnen', 'kommen', 'heeschen', 'sinn'], correctAnswer: 'wunnen' },
          { type: 'orderWords', id: 'a1-obj2-b3-e9', translation: 'Eu venho do Brasil', words: ['Ech', 'kommen', 'aus', 'Brasilien'], correctOrder: ['Ech', 'kommen', 'aus', 'Brasilien'] },
          { type: 'translate', id: 'a1-obj2-b3-e10', promptLang: 'lu', prompt: 'Wou wunns du?', acceptedAnswers: ['Onde você mora?'] },
        ],
      },
      {
        id: 'a1-obj2-b4',
        title: 'Barra 4 · Aplicação',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj2-b4-e1', promptLang: 'pt', prompt: 'Alguém te pergunta "Wéi heeschs du?". O que ela quer saber?', options: ['Seu nome', 'Sua idade', 'Onde você mora', 'De onde você vem'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj2-b4-e2', promptLang: 'lu', prompt: 'Dat ass mäi Frënd', acceptedAnswers: ['Este é meu amigo'] },
          { type: 'fillBlank', id: 'a1-obj2-b4-e3', promptLang: 'lu', sentence: 'Dat ass ___ Frënd', translation: 'Este é meu amigo', options: ['mäi', 'meng', 'eis', 'däin'], correctAnswer: 'mäi' },
          { type: 'multipleChoice', id: 'a1-obj2-b4-e4', promptLang: 'pt', prompt: 'Você quer perguntar a idade de alguém. O que você diz?', options: ['Wéi al bass du?', 'Wou wunns du?', 'Wéi heeschs du?', 'Vu wou kënns du?'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj2-b4-e5', promptLang: 'lu', prompt: 'Ech kommen aus Lëtzebuerg an ech wunnen zu Portugal', acceptedAnswers: ['Eu venho de Luxemburgo e eu moro em Portugal'] },
          { type: 'multipleChoice', id: 'a1-obj2-b4-e6', promptLang: 'pt', prompt: 'Você quer saber de onde alguém vem. O que você pergunta?', options: ['Vu wou kënns du?', 'Wou wunns du?', 'Wéi al bass du?', 'Wéi heeschs du?'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj2-b4-e7', promptLang: 'pt', prompt: 'Eu tenho vinte e cinco anos', acceptedAnswers: ['Ech sinn fënnefanzwanzeg Joer al'] },
          { type: 'fillBlank', id: 'a1-obj2-b4-e8', promptLang: 'lu', sentence: 'Ech sinn ___ Joer al', translation: 'Eu tenho vinte e cinco anos', options: ['fënnefanzwanzeg', 'Lëtzebuerg', 'Numm', 'wunnen'], correctAnswer: 'fënnefanzwanzeg' },
          { type: 'multipleChoice', id: 'a1-obj2-b4-e9', promptLang: 'lu', prompt: 'mäin Numm', options: ['Meu nome', 'Meu país', 'Minha idade', 'Minha casa'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj2-b4-e10', promptLang: 'pt', prompt: 'Meu nome é Ana', acceptedAnswers: ['Mäin Numm ass Ana'] },
        ],
      },
      {
        id: 'a1-obj2-b5',
        title: 'Barra 5 · Desafio',
        exercises: [
          { type: 'translate', id: 'a1-obj2-b5-e1', promptLang: 'pt', prompt: 'Nome', acceptedAnswers: ['den Numm', 'Numm'] },
          { type: 'fillBlank', id: 'a1-obj2-b5-e2', promptLang: 'lu', sentence: 'Wéi ___ bass du?', translation: 'Quantos anos você tem?', options: ['al', 'Numm', 'Land', 'gutt'], correctAnswer: 'al' },
          { type: 'orderWords', id: 'a1-obj2-b5-e3', translation: 'De onde você vem?', words: ['Vu', 'wou', 'kënns', 'du?'], correctOrder: ['Vu', 'wou', 'kënns', 'du?'] },
          { type: 'translate', id: 'a1-obj2-b5-e4', promptLang: 'lu', prompt: 'Ech wunnen zu Lëtzebuerg an ech kommen aus Portugal', acceptedAnswers: ['Eu moro em Luxemburgo e eu venho de Portugal'] },
          { type: 'multipleChoice', id: 'a1-obj2-b5-e5', promptLang: 'pt', prompt: 'Qual país isso representa: Lëtzebuerg?', options: ['Luxemburgo', 'Portugal', 'Brasil', 'França'], correctIndex: 0 },
          { type: 'fillBlank', id: 'a1-obj2-b5-e6', promptLang: 'lu', sentence: 'Ech ___ aus Brasilien', translation: 'Eu venho do Brasil', options: ['kommen', 'wunnen', 'heeschen', 'sinn'], correctAnswer: 'kommen' },
          { type: 'match', id: 'a1-obj2-b5-e7', pairs: [
            { pt: 'Nome', lu: 'den Numm' },
            { pt: 'Idade', lu: 'den Alter' },
            { pt: 'País', lu: "d'Land" },
            { pt: 'Morar', lu: 'wunnen' },
          ] },
          { type: 'translate', id: 'a1-obj2-b5-e8', promptLang: 'pt', prompt: 'Eu tenho vinte anos', acceptedAnswers: ['Ech sinn zwanzeg Joer al'] },
          { type: 'orderWords', id: 'a1-obj2-b5-e9', translation: 'Eu moro em Luxemburgo', words: ['Ech', 'wunnen', 'zu', 'Lëtzebuerg'], correctOrder: ['Ech', 'wunnen', 'zu', 'Lëtzebuerg'] },
          { type: 'multipleChoice', id: 'a1-obj2-b5-e10', promptLang: 'lu', prompt: 'Wéi al bass du?', options: ['Quantos anos você tem?', 'Onde você mora?', 'Qual é seu nome?', 'De onde você vem?'], correctIndex: 0 },
        ],
      },
    ],
  },
  {
    id: 'a1-obj3',
    title: 'Números',
    description: 'Contar de 0 a 100 e usar números no dia a dia',
    level: 'A1-INICIANTE',
    kind: 'objective',
    icon: '🔢',
    lessons: [
      {
        id: 'a1-obj3-b1',
        title: 'Barra 1 · Introdução (11-19)',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj3-b1-e1', promptLang: 'lu', prompt: 'eelef', options: ['11', '10', '12', '9'], correctIndex: 0 },
          { type: 'multipleChoice', id: 'a1-obj3-b1-e2', promptLang: 'lu', prompt: 'zwielef', options: ['12', '11', '13', '10'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b1-e3', promptLang: 'pt', prompt: '13', acceptedAnswers: ['dräizéng'] },
          { type: 'multipleChoice', id: 'a1-obj3-b1-e4', promptLang: 'lu', prompt: 'véierzéng', options: ['14', '13', '15', '4'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b1-e5', promptLang: 'pt', prompt: '15', acceptedAnswers: ['fofzéng'] },
          { type: 'match', id: 'a1-obj3-b1-e6', pairs: [
            { pt: '11', lu: 'eelef' },
            { pt: '12', lu: 'zwielef' },
            { pt: '13', lu: 'dräizéng' },
            { pt: '14', lu: 'véierzéng' },
          ] },
          { type: 'multipleChoice', id: 'a1-obj3-b1-e7', promptLang: 'lu', prompt: 'siechzéng', options: ['16', '17', '15', '6'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b1-e8', promptLang: 'pt', prompt: '17', acceptedAnswers: ['siwwenzéng'] },
          { type: 'multipleChoice', id: 'a1-obj3-b1-e9', promptLang: 'lu', prompt: 'uechtzéng', options: ['18', '8', '19', '17'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b1-e10', promptLang: 'pt', prompt: '19', acceptedAnswers: ['nonzéng'] },
        ],
      },
      {
        id: 'a1-obj3-b2',
        title: 'Barra 2 · Compreensão (20-100)',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj3-b2-e1', promptLang: 'lu', prompt: 'zwanzeg', options: ['20', '12', '2', '200'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b2-e2', promptLang: 'pt', prompt: '30', acceptedAnswers: ['drësseg'] },
          { type: 'multipleChoice', id: 'a1-obj3-b2-e3', promptLang: 'lu', prompt: 'véierzeg', options: ['40', '14', '4', '400'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b2-e4', promptLang: 'pt', prompt: '50', acceptedAnswers: ['fofzeg'] },
          { type: 'match', id: 'a1-obj3-b2-e5', pairs: [
            { pt: '20', lu: 'zwanzeg' },
            { pt: '30', lu: 'drësseg' },
            { pt: '40', lu: 'véierzeg' },
            { pt: '50', lu: 'fofzeg' },
          ] },
          { type: 'multipleChoice', id: 'a1-obj3-b2-e6', promptLang: 'lu', prompt: 'sechzeg', options: ['60', '16', '6', '600'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b2-e7', promptLang: 'pt', prompt: '70', acceptedAnswers: ['siwwenzeg'] },
          { type: 'multipleChoice', id: 'a1-obj3-b2-e8', promptLang: 'lu', prompt: 'achtzeg', options: ['80', '18', '8', '800'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b2-e9', promptLang: 'pt', prompt: '90', acceptedAnswers: ['nonzeg'] },
          { type: 'multipleChoice', id: 'a1-obj3-b2-e10', promptLang: 'lu', prompt: 'honnert', options: ['100', '10', '1000', '19'], correctIndex: 0 },
        ],
      },
      {
        id: 'a1-obj3-b3',
        title: 'Barra 3 · Construção',
        exercises: [
          { type: 'fillBlank', id: 'a1-obj3-b3-e1', promptLang: 'lu', sentence: 'Ech sinn ___ Joer al', translation: 'Eu tenho vinte e cinco anos', options: ['fënnefanzwanzeg', 'zwanzeg', 'honnert', 'zéng'], correctAnswer: 'fënnefanzwanzeg' },
          { type: 'translate', id: 'a1-obj3-b3-e2', promptLang: 'lu', prompt: 'Ech hu fofzeg Euro', acceptedAnswers: ['Eu tenho cinquenta euros'] },
          { type: 'orderWords', id: 'a1-obj3-b3-e3', translation: 'Eu tenho cinquenta euros', words: ['Ech', 'hu', 'fofzeg', 'Euro'], correctOrder: ['Ech', 'hu', 'fofzeg', 'Euro'] },
          { type: 'fillBlank', id: 'a1-obj3-b3-e4', promptLang: 'lu', sentence: "D'Buch kascht ___ Euro", translation: 'O livro custa dez euros', options: ['zéng', 'Numm', 'Land', 'gutt'], correctAnswer: 'zéng' },
          { type: 'translate', id: 'a1-obj3-b3-e5', promptLang: 'pt', prompt: 'Vinte e cinco', acceptedAnswers: ['fënnefanzwanzeg'] },
          { type: 'orderWords', id: 'a1-obj3-b3-e6', translation: 'O café custa três euros', words: ['De', 'Kaffi', 'kascht', 'dräi', 'Euro'], correctOrder: ['De', 'Kaffi', 'kascht', 'dräi', 'Euro'], itemIds: ['word:kaffi'] },
          { type: 'translate', id: 'a1-obj3-b3-e7', promptLang: 'lu', prompt: 'Mir sinn zéng Frënn', acceptedAnswers: ['Nós somos dez amigos'] },
          { type: 'fillBlank', id: 'a1-obj3-b3-e8', promptLang: 'lu', sentence: 'D\'Wunneng kascht ___ Euro', translation: 'O apartamento custa cem euros', options: ['honnert', 'Joer', 'Frënn', 'Numm'], correctAnswer: 'honnert' },
          { type: 'orderWords', id: 'a1-obj3-b3-e9', translation: 'Eu tenho vinte anos', words: ['Ech', 'sinn', 'zwanzeg', 'Joer', 'al'], correctOrder: ['Ech', 'sinn', 'zwanzeg', 'Joer', 'al'] },
          { type: 'translate', id: 'a1-obj3-b3-e10', promptLang: 'pt', prompt: 'Cem', acceptedAnswers: ['honnert'] },
        ],
      },
      {
        id: 'a1-obj3-b4',
        title: 'Barra 4 · Aplicação',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj3-b4-e1', promptLang: 'lu', prompt: 'Wéi ass deng Telefonsnummer?', options: ['Qual é o seu telefone?', 'Qual é o seu nome?', 'Quantos anos você tem?', 'Onde você mora?'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b4-e2', promptLang: 'lu', prompt: 'Wéi vill kascht dat?', acceptedAnswers: ['Quanto custa isso?'] },
          { type: 'fillBlank', id: 'a1-obj3-b4-e3', promptLang: 'lu', sentence: 'Wéi vill ___ dat?', translation: 'Quanto custa isso?', options: ['kascht', 'ass', 'heescht', 'wunnt'], correctAnswer: 'kascht' },
          { type: 'multipleChoice', id: 'a1-obj3-b4-e4', promptLang: 'pt', prompt: 'Quanto custa isso?', options: ['Wéi vill kascht dat?', 'Wéi al bass du?', 'Wou wunns du?', 'Wéi heeschs du?'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b4-e5', promptLang: 'pt', prompt: 'Dez euros', acceptedAnswers: ['zéng Euro'] },
          { type: 'orderWords', id: 'a1-obj3-b4-e6', translation: 'Quanto custa isso?', words: ['Wéi', 'vill', 'kascht', 'dat?'], correctOrder: ['Wéi', 'vill', 'kascht', 'dat?'] },
          { type: 'fillBlank', id: 'a1-obj3-b4-e7', promptLang: 'lu', sentence: 'Meng Telefonsnummer ass ___', translation: 'Meu telefone é noventa...', options: ['nonzeg', 'gutt', 'frou', 'midd'], correctAnswer: 'nonzeg' },
          { type: 'translate', id: 'a1-obj3-b4-e8', promptLang: 'lu', prompt: 'Dat kascht honnert Euro', acceptedAnswers: ['Isso custa cem euros'] },
          { type: 'translate', id: 'a1-obj3-b4-e9', promptLang: 'pt', prompt: 'Meu telefone', acceptedAnswers: ['meng Telefonsnummer'] },
          { type: 'fillBlank', id: 'a1-obj3-b4-e10', promptLang: 'lu', sentence: 'Dat kascht ___ Euro', translation: 'Isso custa cinquenta euros', options: ['fofzeg', 'Numm', 'Land', 'gutt'], correctAnswer: 'fofzeg' },
        ],
      },
      {
        id: 'a1-obj3-b5',
        title: 'Barra 5 · Desafio',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj3-b5-e1', promptLang: 'lu', prompt: 'honnert', options: ['100', '10', '1000', '19'], correctIndex: 0 },
          { type: 'fillBlank', id: 'a1-obj3-b5-e2', promptLang: 'lu', sentence: 'Ech sinn ___ Joer al', translation: 'Eu tenho vinte e cinco anos', options: ['fënnefanzwanzeg', 'honnert', 'zwee', 'eent'], correctAnswer: 'fënnefanzwanzeg' },
          { type: 'orderWords', id: 'a1-obj3-b5-e3', translation: 'Quanto custa isso?', words: ['Wéi', 'vill', 'kascht', 'dat?'], correctOrder: ['Wéi', 'vill', 'kascht', 'dat?'] },
          { type: 'translate', id: 'a1-obj3-b5-e4', promptLang: 'pt', prompt: 'Noventa', acceptedAnswers: ['nonzeg'] },
          { type: 'match', id: 'a1-obj3-b5-e5', pairs: [
            { pt: '20', lu: 'zwanzeg' },
            { pt: '50', lu: 'fofzeg' },
            { pt: '80', lu: 'achtzeg' },
            { pt: '100', lu: 'honnert' },
          ] },
          { type: 'fillBlank', id: 'a1-obj3-b5-e6', promptLang: 'lu', sentence: 'Dat kascht ___ Euro', translation: 'Isso custa dez euros', options: ['zéng', 'Numm', 'Land', 'gutt'], correctAnswer: 'zéng' },
          { type: 'translate', id: 'a1-obj3-b5-e7', promptLang: 'lu', prompt: 'Wéi vill kascht dat?', acceptedAnswers: ['Quanto custa isso?'] },
          { type: 'multipleChoice', id: 'a1-obj3-b5-e8', promptLang: 'lu', prompt: 'siechzéng', options: ['16', '17', '15', '6'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj3-b5-e9', promptLang: 'pt', prompt: 'Doze', acceptedAnswers: ['zwielef'] },
          { type: 'fillBlank', id: 'a1-obj3-b5-e10', promptLang: 'lu', sentence: 'Ech hu ___ Euro', translation: 'Eu tenho cinquenta euros', options: ['fofzeg', 'Numm', 'Land', 'gutt'], correctAnswer: 'fofzeg' },
        ],
      },
    ],
  },
  {
    id: 'a1-obj4',
    title: 'Cores e Formas',
    description: 'Descrever objetos por cor, tamanho e forma',
    level: 'A1-INICIANTE',
    kind: 'objective',
    icon: '🎨',
    lessons: [
      {
        id: 'a1-obj4-b1',
        title: 'Barra 1 · Introdução',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj4-b1-e1', promptLang: 'lu', prompt: 'rout', options: ['Vermelho', 'Azul', 'Verde', 'Amarelo'], correctIndex: 0 },
          { type: 'multipleChoice', id: 'a1-obj4-b1-e2', promptLang: 'lu', prompt: 'hell', options: ['Claro', 'Escuro', 'Grande', 'Pequeno'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj4-b1-e3', promptLang: 'pt', prompt: 'Escuro', acceptedAnswers: ['donkel'] },
          { type: 'multipleChoice', id: 'a1-obj4-b1-e4', promptLang: 'lu', prompt: 'grouss', options: ['Grande', 'Pequeno', 'Claro', 'Escuro'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj4-b1-e5', promptLang: 'pt', prompt: 'Pequeno', acceptedAnswers: ['kleng'] },
          { type: 'match', id: 'a1-obj4-b1-e6', pairs: [
            { pt: 'Claro', lu: 'hell' },
            { pt: 'Escuro', lu: 'donkel' },
            { pt: 'Grande', lu: 'grouss' },
            { pt: 'Pequeno', lu: 'kleng' },
          ] },
          { type: 'multipleChoice', id: 'a1-obj4-b1-e7', promptLang: 'lu', prompt: 'e Krees', options: ['Um círculo', 'Um quadrado', 'Um triângulo', 'Uma cor'], correctIndex: 0, hint: "'Krees' é masculino: 'e Krees'." },
          { type: 'translate', id: 'a1-obj4-b1-e8', promptLang: 'pt', prompt: 'Quadrado', acceptedAnswers: ['e Quadrat', 'Quadrat'] },
          { type: 'multipleChoice', id: 'a1-obj4-b1-e9', promptLang: 'lu', prompt: 'en Dräieck', options: ['Um triângulo', 'Um círculo', 'Um quadrado', 'Uma cor'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj4-b1-e10', promptLang: 'pt', prompt: 'Círculo', acceptedAnswers: ['e Krees', 'Krees'] },
        ],
      },
      {
        id: 'a1-obj4-b2',
        title: 'Barra 2 · Compreensão',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj4-b2-e1', promptLang: 'lu', prompt: 'Dëst ass hell', options: ['Isto é claro', 'Isto é escuro', 'Isto é grande', 'Isto é pequeno'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj4-b2-e2', promptLang: 'lu', prompt: 'Dëst ass donkel', acceptedAnswers: ['Isto é escuro'] },
          { type: 'fillBlank', id: 'a1-obj4-b2-e3', promptLang: 'lu', sentence: 'Dëst ass ganz ___', translation: 'Isto é muito grande', options: ['grouss', 'hell', 'donkel', 'kleng'], correctAnswer: 'grouss' },
          { type: 'multipleChoice', id: 'a1-obj4-b2-e4', promptLang: 'pt', prompt: 'Isto é pequeno', options: ['Dëst ass kleng', 'Dëst ass grouss', 'Dëst ass hell', 'Dëst ass donkel'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj4-b2-e5', promptLang: 'lu', prompt: 'Dëst ass e Krees', acceptedAnswers: ['Isto é um círculo'] },
          { type: 'match', id: 'a1-obj4-b2-e6', pairs: [
            { pt: 'Isto é claro', lu: 'Dëst ass hell' },
            { pt: 'Isto é escuro', lu: 'Dëst ass donkel' },
            { pt: 'Isto é grande', lu: 'Dëst ass grouss' },
            { pt: 'Isto é pequeno', lu: 'Dëst ass kleng' },
          ] },
          { type: 'multipleChoice', id: 'a1-obj4-b2-e7', promptLang: 'lu', prompt: 'Dëst ass e Quadrat', options: ['Isto é um quadrado', 'Isto é um círculo', 'Isto é um triângulo', 'Isto é vermelho'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj4-b2-e8', promptLang: 'lu', prompt: 'Dëst ass en Dräieck', acceptedAnswers: ['Isto é um triângulo'] },
          { type: 'fillBlank', id: 'a1-obj4-b2-e9', promptLang: 'lu', sentence: 'Dëst ass ___', translation: 'Isto é um círculo', options: ['e Krees', 'rout', 'hell', 'grouss'], correctAnswer: 'e Krees' },
          { type: 'multipleChoice', id: 'a1-obj4-b2-e10', promptLang: 'pt', prompt: 'Isto é um triângulo', options: ['Dëst ass en Dräieck', 'Dëst ass e Krees', 'Dëst ass e Quadrat', 'Dëst ass rout'], correctIndex: 0 },
        ],
      },
      {
        id: 'a1-obj4-b3',
        title: 'Barra 3 · Construção',
        exercises: [
          { type: 'orderWords', id: 'a1-obj4-b3-e1', translation: 'Isto é um círculo', words: ['Dëst', 'ass', 'e', 'Krees'], correctOrder: ['Dëst', 'ass', 'e', 'Krees'] },
          { type: 'fillBlank', id: 'a1-obj4-b3-e2', promptLang: 'lu', sentence: 'Dëst ass ganz ___', translation: 'Isto é muito escuro', options: ['donkel', 'e Krees', 'e Quadrat', 'en Dräieck'], correctAnswer: 'donkel' },
          { type: 'orderWords', id: 'a1-obj4-b3-e3', translation: 'Isto é um triângulo', words: ['Dëst', 'ass', 'en', 'Dräieck'], correctOrder: ['Dëst', 'ass', 'en', 'Dräieck'] },
          { type: 'translate', id: 'a1-obj4-b3-e4', promptLang: 'pt', prompt: 'Isto é grande e claro', acceptedAnswers: ['Dëst ass grouss a hell'] },
          { type: 'fillBlank', id: 'a1-obj4-b3-e5', promptLang: 'lu', sentence: 'Dëst ass grouss ___ hell', translation: 'Isto é grande e claro', options: ['a', 'de', 'en', 'Krees'], correctAnswer: 'a' },
          { type: 'orderWords', id: 'a1-obj4-b3-e6', translation: 'Isto é pequeno e escuro', words: ['Dëst', 'ass', 'kleng', 'a', 'donkel'], correctOrder: ['Dëst', 'ass', 'kleng', 'a', 'donkel'] },
          { type: 'translate', id: 'a1-obj4-b3-e7', promptLang: 'lu', prompt: 'Dëst ass e Quadrat, rout a grouss', acceptedAnswers: ['Isto é um quadrado, vermelho e grande'] },
          { type: 'fillBlank', id: 'a1-obj4-b3-e8', promptLang: 'lu', sentence: 'Dëst ass ___, rout a grouss', translation: 'Isto é um quadrado, vermelho e grande', options: ['e Quadrat', 'hell', 'donkel', 'kleng'], correctAnswer: 'e Quadrat' },
          { type: 'orderWords', id: 'a1-obj4-b3-e9', translation: 'Isto é grande', words: ['Dëst', 'ass', 'grouss'], correctOrder: ['Dëst', 'ass', 'grouss'] },
          { type: 'translate', id: 'a1-obj4-b3-e10', promptLang: 'pt', prompt: 'Isto é pequeno', acceptedAnswers: ['Dëst ass kleng'] },
        ],
      },
      {
        id: 'a1-obj4-b4',
        title: 'Barra 4 · Aplicação',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj4-b4-e1', promptLang: 'pt', prompt: 'Você quer descrever algo redondo e vermelho. O que você diz?', options: ['Dëst ass e Krees, rout', 'Dëst ass en Dräieck', 'Dëst ass donkel', 'Dëst ass grouss'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj4-b4-e2', promptLang: 'lu', prompt: "Wéi ass d'Faarf?", acceptedAnswers: ['Qual é a cor?'], hint: "'Faarf' é feminino: 'd'Faarf'." },
          { type: 'fillBlank', id: 'a1-obj4-b4-e3', promptLang: 'lu', sentence: "Wéi ass d'___?", translation: 'Qual é a cor?', options: ['Faarf', 'Krees', 'Quadrat', 'Dräieck'], correctAnswer: 'Faarf' },
          { type: 'multipleChoice', id: 'a1-obj4-b4-e4', promptLang: 'pt', prompt: 'Qual é a cor?', options: ["Wéi ass d'Faarf?", "Wéi ass d'Land?", 'Wéi al bass du?', 'Wou wunns du?'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj4-b4-e5', promptLang: 'pt', prompt: 'A cor é vermelha', acceptedAnswers: ["D'Faarf ass rout"] },
          { type: 'multipleChoice', id: 'a1-obj4-b4-e6', promptLang: 'lu', prompt: "D'Faarf ass gréng", options: ['A cor é verde', 'A cor é azul', 'A cor é branca', 'A cor é preta'], correctIndex: 0 },
          { type: 'fillBlank', id: 'a1-obj4-b4-e7', promptLang: 'lu', sentence: "D'Faarf ass ___", translation: 'A cor é verde', options: ['gréng', 'e Krees', 'en Dräieck', 'grouss'], correctAnswer: 'gréng' },
          { type: 'translate', id: 'a1-obj4-b4-e8', promptLang: 'lu', prompt: "Ech hu gär d'Faarf blo", acceptedAnswers: ['Eu gosto da cor azul'], hint: "'gär hunn' significa gostar." },
          { type: 'multipleChoice', id: 'a1-obj4-b4-e9', promptLang: 'pt', prompt: 'Você quer dizer que gosta da cor vermelha. O que você diz?', options: ["Ech hu gär d'Faarf rout", 'Dëst ass rout', "D'Faarf ass rout", 'Ech sinn rout'], correctIndex: 0 },
          { type: 'translate', id: 'a1-obj4-b4-e10', promptLang: 'pt', prompt: 'Eu gosto da cor verde', acceptedAnswers: ["Ech hu gär d'Faarf gréng"] },
        ],
      },
      {
        id: 'a1-obj4-b5',
        title: 'Barra 5 · Desafio',
        exercises: [
          { type: 'multipleChoice', id: 'a1-obj4-b5-e1', promptLang: 'lu', prompt: 'rout', options: ['Vermelho', 'Azul', 'Verde', 'Amarelo'], correctIndex: 0 },
          { type: 'fillBlank', id: 'a1-obj4-b5-e2', promptLang: 'lu', sentence: 'Dëst ass ganz ___', translation: 'Isto é muito grande', options: ['grouss', 'e Krees', 'en Dräieck', 'e Quadrat'], correctAnswer: 'grouss' },
          { type: 'orderWords', id: 'a1-obj4-b5-e3', translation: 'Qual é a cor?', words: ['Wéi', 'ass', "d'Faarf?"], correctOrder: ['Wéi', 'ass', "d'Faarf?"] },
          { type: 'translate', id: 'a1-obj4-b5-e4', promptLang: 'lu', prompt: "D'Faarf ass hell", acceptedAnswers: ['A cor é clara'] },
          { type: 'match', id: 'a1-obj4-b5-e5', pairs: [
            { pt: 'Círculo', lu: 'e Krees' },
            { pt: 'Quadrado', lu: 'e Quadrat' },
            { pt: 'Triângulo', lu: 'en Dräieck' },
            { pt: 'Cor', lu: "d'Faarf" },
          ] },
          { type: 'fillBlank', id: 'a1-obj4-b5-e6', promptLang: 'lu', sentence: "D'Faarf ass ___", translation: 'A cor é escura', options: ['donkel', 'e Krees', 'grouss', 'kleng'], correctAnswer: 'donkel' },
          { type: 'translate', id: 'a1-obj4-b5-e7', promptLang: 'pt', prompt: 'Eu gosto da cor azul', acceptedAnswers: ["Ech hu gär d'Faarf blo"] },
          { type: 'multipleChoice', id: 'a1-obj4-b5-e8', promptLang: 'lu', prompt: 'Dëst ass en Dräieck', options: ['Isto é um triângulo', 'Isto é um círculo', 'Isto é um quadrado', 'Isto é grande'], correctIndex: 0 },
          { type: 'orderWords', id: 'a1-obj4-b5-e9', translation: 'Isto é um quadrado', words: ['Dëst', 'ass', 'e', 'Quadrat'], correctOrder: ['Dëst', 'ass', 'e', 'Quadrat'] },
          { type: 'translate', id: 'a1-obj4-b5-e10', promptLang: 'pt', prompt: 'A cor é verde', acceptedAnswers: ["D'Faarf ass gréng"] },
        ],
      },
    ],
  },
];
